'use client';
import { useState, useEffect, useRef, type CSSProperties } from 'react';
import { flushSync } from 'react-dom';
import { Network, LayoutDashboard, BriefcaseBusiness, Database, TrendingUp, ChevronRight, ArrowUpRight, ShieldCheck, Target, Workflow, CircleCheck, Info, Download, X, ArrowRight, Users } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarContent, SidebarHeader, SidebarFooter, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from '@/components/ui/sidebar';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { db, roles, people, scenarios, capabilities, globalMetrics, personById, roleById, capById, type Person } from './model';
import { GraphView, type DetailRef } from './graph-view';
import { WallView } from './wall-view';
import { BusinessView } from './business-view';
import { DataView } from './data-view';
import { GrowthView, type GrowthPlan } from './growth-view';
import { DetailPanel } from './detail-panel';
import { Badge, Note } from './ui-parts';
import { ManagementProvider, useManagement } from './management-context';
import { OrganizationView } from './organization-view';
import { GovernanceView } from './governance-view';
import { AuthorizationView, EvaluationView } from './evaluation-view';
import { SupplyView, DiagnosisView } from './operations-view';
import { TalentView } from './talent-view';
import { currentVersion, supply } from './management-model';
import { KPI } from './management-ui';
const navigation=[{id:'overview',label:'体系全景',icon:LayoutDashboard,description:'从业务保障看岗位能力现状，追溯标准、证据与管理行动。'},{id:'wall',label:'岗位能力墙',icon:BriefcaseBusiness,description:'统一岗位标尺，分别查看达标项、能力差距与证据缺口。'},{id:'graph',label:'图谱探索',icon:Network,description:'横向连接岗位与协同关系，纵向追溯任务、标准与依据。'},{id:'organization',label:'组织与岗位',icon:Users,description:'管理组织、岗位序列、编制和人员任职，查看兼岗、支援与任职历史。'},{id:'governance',label:'体系与版本',icon:Network,description:'维护业务对象和标准关系，校验变更影响，审核后发布新版本。'},{id:'authorization',label:'场景上岗授权',icon:ShieldCheck,description:'按场景逐项核验能力、证据、任职与授权，保留上岗判断依据。'},{id:'evaluation',label:'评价与复核',icon:CircleCheck,description:'核验证据、校准观察、复核结果并处理员工异议。'},{id:'supply',label:'能力供需与预警',icon:Users,description:'按场景、班组和时段查看能力供给，评估支援安排及后备风险。'},{id:'diagnosis',label:'业务结果诊断',icon:Target,description:'从服务异常追查业务原因，明确整改责任并跟踪后续表现。'},{id:'talent',label:'人才梯队',icon:TrendingUp,description:'连接发展意愿、目标岗位、导师和必需实践，形成后备培养路径。'},{id:'business',label:'业务架构',icon:Workflow,description:'把业务职责、场景、任务转化为可观察的能力要求。'},{id:'data',label:'数据治理',icon:Database,description:'贯通数据目录、血缘、标准、标签与质量，让能力依据可追溯。'},{id:'growth',label:'成长路径',icon:TrendingUp,description:'对照具体目标安排训练与补证，经复测复核后更新能力记录。'}];
interface ModelTool {name:string;description:string;title?:string;inputSchema:object;annotations:{readOnlyHint:boolean;untrustedContentHint:boolean};execute:(input:unknown)=>unknown}
interface ModelContext {registerTool:(tool:ModelTool,options:{signal:AbortSignal})=>void|Promise<void>}
export default function CapabilityApp(){return <ManagementProvider><CapabilityWorkspace/></ManagementProvider>}
function CapabilityWorkspace(){
 const {state:management,mutate,message,notify,storageStatus}=useManagement();
 const [page,setPage]=useState('overview');const [roleId,setRoleId]=useState(roles[1].id);const [personId,setPersonId]=useState(people.find(p=>p.name==='林悦')!.id);const [assetId,setAssetId]=useState(db.dataAssets.find(a=>a.name.includes('质检'))?.id||db.dataAssets[0].id);const [dataTab,setDataTab]=useState('catalog');const [detailStack,setDetailStack]=useState<DetailRef[]>([]);const plans=management.legacyPlans;const setPlans=(plans:GrowthPlan[])=>mutate(s=>{s.legacyPlans=plans});const [notice,setNotice]=useState('');const [aboutOpen,setAboutOpen]=useState(false);
 const metrics=globalMetrics();const current=navigation.find(n=>n.id===page)||navigation[0];
 const navigate=(id:string)=>{if(!navigation.some(n=>n.id===id))return;setPage(id);setNotice('');if(typeof window!=='undefined'){window.history.pushState({},'',`#${id}`);window.scrollTo({top:0,behavior:'instant'})}};
 useEffect(()=>{const sync=()=>{const hash=window.location.hash.slice(1);if(navigation.some(n=>n.id===hash))setPage(hash)};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
 const openDetail=(d:DetailRef)=>setDetailStack(s=>[...s,d]);
 const openGrowth=(p:Person)=>{setPersonId(p.id);setDetailStack([]);navigate('growth')};
 const openData=(id:string,tab:string)=>{setAssetId(id);setDataTab(tab);setDetailStack([]);navigate('data')};
 const stateRef=useRef({page,roleId,personId,plans});stateRef.current={page,roleId,personId,plans};
 useEffect(()=>{const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const fail=()=>{/* Optional browser integration must not affect the user interface. */};const register=(tool:ModelTool)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(fail)}catch{fail()}};
 register({name:'read_capability_workspace',title:'Read capability workspace',description:'Read the current prototype view and synthetic roles and personnel. This does not change page state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(input===null||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');return {...stateRef.current,roles:roles.map(r=>({id:r.id,name:r.name})),people:people.map(p=>({id:p.id,name:p.name,roleId:p.roleId})),synthetic:true}}});
 register({name:'navigate_capability_workspace',title:'Open a capability view',description:'Navigate the visible prototype to a view, optionally selecting a valid role and employee. Does not change ratings or evidence.',inputSchema:{type:'object',properties:{page:{type:'string',enum:navigation.map(n=>n.id)},roleId:{type:'string'},personId:{type:'string'}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object')throw new Error('Expected object');const value=input as Record<string,unknown>;if(Object.keys(value).some(k=>!['page','roleId','personId'].includes(k)))throw new Error('Unknown field');if(typeof value.page!=='string'||!navigation.some(n=>n.id===value.page))throw new Error('Unknown page');if(value.roleId!==undefined&&!roles.some(r=>r.id===value.roleId))throw new Error('Unknown role');if(value.personId!==undefined&&!people.some(p=>p.id===value.personId))throw new Error('Unknown person');flushSync(()=>{setPage(value.page as string);if(value.roleId)setRoleId(value.roleId as string);if(value.personId)setPersonId(value.personId as string)});window.history.pushState({},'',`#${value.page}`);return {page:value.page,roleId:stateRef.current.roleId,personId:stateRef.current.personId,synthetic:true}}});return()=>lifecycle.abort()},[]);
 return <SidebarProvider style={{'--sidebar-width':'218px'} as CSSProperties}><Sidebar className="app-sidebar"><SidebarHeader className="brand"><span className="brand-mark"><Network size={27}/></span><div><strong>95598</strong><span>岗位能力图谱</span></div></SidebarHeader><SidebarContent><div className="nav-caption">工作空间</div><SidebarMenu className="nav-menu">{navigation.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton className="nav-link" isActive={page===n.id} onClick={()=>navigate(n.id)}><n.icon size={19}/><span>{n.label}</span>{page===n.id&&<span className="nav-dot"/>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><span>体系连接，让成长有据可循</span><div className="mini-flow"><Workflow/><i/><BriefcaseBusiness/><i/><Target/></div><p>业务有标准 · 岗位有画像<br/>能力有依据 · 成长有方向</p></div></SidebarContent><SidebarFooter className="sidebar-bottom"><button className="version" onClick={()=>setAboutOpen(true)}><i className="live-dot"/>演示工作空间 <span>V2.0</span></button><div className="user-row"><span className="avatar">管</span><div><b>能力体系管理员</b><small>95598 客户服务中心</small></div><ShieldCheck size={17}/></div></SidebarFooter></Sidebar>
 <div className="app-shell"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="sidebar-toggle"/><span>95598 客户服务中心</span><ChevronRight size={14}/><b>{current.label}</b></div><div className="topbar-right"><span className="mock-badge">模拟数据</span><span className="top-date">2026年9月 · 演示快照</span><button className="help-button" aria-label="演示说明与方案依据" onClick={()=>setAboutOpen(true)}><Info size={18}/></button><span className="avatar small">管</span></div></header><main className="workspace"><div className="page-heading"><div><div className="eyebrow">CAPABILITY ATLAS <span>/ {String(navigation.findIndex(n=>n.id===page)+1).padStart(2,'0')}</span></div><h1>{current.label}</h1><p>{current.description}</p></div><div className="heading-actions"><span className="freshness"><i className="live-dot"/>标准版本 · {currentVersion(management)}</span><button className="button primary" onClick={()=>page==='wall'?navigate('graph'):navigate('wall')}>{page==='wall'?<Network size={16}/>:<BriefcaseBusiness size={16}/>}查看{page==='wall'?'体系图谱':'岗位能力墙'}<ArrowUpRight size={16}/></button></div></div>
 {message&&<div className="notice-banner management-message" role="status"><CircleCheck size={18}/><span>{message}</span><button aria-label="关闭操作提示" onClick={()=>notify('')}><X size={16}/></button></div>}
 {notice&&<div className="notice-banner" role="status"><CircleCheck size={18}/><span>{notice}</span><button aria-label="关闭提示" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {page==='overview'&&<><KPI items={[{label:'当班场景缺口',value:['POL-SCN-03','POL-SCN-05'].reduce((n,id)=>n+supply(management,id,'SLOT-1').gap,0),note:'14:00—15:00 · 按场景逐项汇总',onClick:()=>navigate('supply')},{label:'待复核与异议',value:management.assessments.filter(a=>a.status==='待复核').length+management.appeals.filter(a=>a.status!=='已答复').length,note:'查看证据核验与人工确认事项',onClick:()=>navigate('evaluation')},{label:'待办改善事项',value:management.actions.filter(a=>a.status!=='已完成').length,note:'从业务结果与标准变更追到负责人',onClick:()=>navigate('diagnosis')},{label:'培养中的后备',value:management.development.filter(d=>d.status!=='后备就绪').length,note:'目标能力、实践经历与导师相连',onClick:()=>navigate('talent')}]}/><div className="stats-grid">{[{label:'业务场景',v:String(scenarios.length),unit:'个',note:`${db.businessDomains.length} 个业务域 · ${db.tasks.length} 项业务任务`,icon:Workflow},{label:'岗位体系',v:String(roles.length),unit:'类岗位',note:`覆盖 ${people.length} 名人员 · ${new Set(people.map(p=>p.team)).size} 个班组`,icon:BriefcaseBusiness},{label:'能力标准',v:String(capabilities.length),unit:'项',note:`${db.capabilityTargets.length} 条岗位星级能力要求`,icon:Target},{label:'可采信能力记录',v:String(metrics.coverage),unit:'%',note:`${metrics.needsEvidence} 名人员需补证或复核`,icon:Database}].map((s,i)=><button className="stat-card" key={s.label} onClick={()=>navigate(['business','wall','business','data'][i])}><div className="stat-label">{s.label}<span className={`stat-icon tone-${i}`}><s.icon size={18}/></span></div><div className="stat-number">{s.v}<span>{s.unit}</span></div><div className="stat-note"><i className={i===3?'amber-dot':'small-line'}/>{s.note}</div></button>)}</div><GraphView roleId={roleId} setRoleId={setRoleId} onDetail={openDetail} onNavigate={navigate}/><div className="foundation-strip"><span className="foundation-icon"><Database size={21}/></span><div><b>数据本体支撑</b><span>每一项能力记录，都可以查找业务依据</span></div><div className="foundation-links">{['数据目录','数据血缘','数据标准','数据标签','数据质量'].map((t,i)=><button key={t} onClick={()=>openData(assetId,['catalog','lineage','standards','tags','quality'][i])}><CircleCheck size={14}/>{t}</button>)}</div><button className="text-button" onClick={()=>navigate('data')}>进入数据治理<ArrowUpRight size={15}/></button></div><div className="section-title"><div><h2>值得关注的成长信号</h2><p>差距类型不同，下一步行动也不同</p></div><button className="text-button" onClick={()=>navigate('wall')}>查看全部人员<ArrowRight size={14}/></button></div><div className="signal-grid">{['林悦','周宁','沈薇'].map(name=>{const p=people.find(p=>p.name===name)!;return <button key={p.id} className="signal-card" onClick={()=>openDetail({type:'person',id:p.id})}><div><span className="avatar">{name}</span><div><b>{name}</b><small>{roleById(p.roleId).name}</small></div><Badge tone={name==='林悦'?'amber':name==='周宁'?'gray':'blue'}>{name==='林悦'?'能力差距':name==='周宁'?'证据缺口':'待复核'}</Badge></div><h3>{capById(p.growthFocus.capabilityId).name}</h3><p>{p.growthFocus.nextAction}</p><span>查看能力与依据<ArrowUpRight size={14}/></span></button>})}</div></>}
 {page==='graph'&&<GraphView roleId={roleId} setRoleId={setRoleId} onDetail={openDetail} onNavigate={navigate} explorer/>}
 {page==='wall'&&<WallView roleId={roleId} setRoleId={setRoleId} onDetail={openDetail} onGrowth={openGrowth}/>}
 {page==='organization'&&<OrganizationView onDetail={openDetail}/>}
 {page==='governance'&&<GovernanceView/>}
 {page==='authorization'&&<AuthorizationView personId={personId} onNavigate={navigate} onPerson={setPersonId}/>}
 {page==='evaluation'&&<EvaluationView personId={personId} onPerson={setPersonId} onDetail={openDetail}/>}
 {page==='supply'&&<SupplyView onNavigate={navigate} onPerson={setPersonId}/>}
 {page==='diagnosis'&&<DiagnosisView onNavigate={navigate} onDetail={openDetail}/>}
 {page==='talent'&&<TalentView onNavigate={navigate} onPerson={setPersonId}/>}
 {page==='business'&&<BusinessView roleId={roleId} onDetail={openDetail}/>}
 {page==='data'&&<DataView assetId={assetId} setAssetId={setAssetId} tab={dataTab} setTab={setDataTab} onDetail={openDetail}/>}
 {page==='growth'&&<GrowthView personId={personId} setPersonId={setPersonId} plans={plans} setPlans={setPlans} onDetail={openDetail} onNotice={setNotice}/>}
 <footer className="page-footer"><span>95598 岗位能力图谱 · 业务体系 × 岗位体系 × 数据体系</span><button onClick={()=>setAboutOpen(true)}>全部数据为合成演示 · {storageStatus}</button></footer></main></div>
 <DetailPanel stack={detailStack} onClose={()=>setDetailStack([])} onBack={()=>setDetailStack(s=>s.slice(0,-1))} onDetail={openDetail} onGrowth={openGrowth} onData={openData}/>
 <Dialog open={aboutOpen} onOpenChange={setAboutOpen}><DialogContent className="about-dialog"><DialogHeader><DialogTitle>演示说明与方案依据</DialogTitle><DialogDescription>95598 岗位能力图谱交互原型</DialogDescription></DialogHeader><div className="about-content"><h3>一套可延伸的体系</h3><p>业务域 → 场景 → 任务，与岗位职责和能力标准相连；能力可横向复用到多个岗位，纵向展开等级、行为标准和证据。能力墙是核心成果，成长应用围绕能力墙展开。</p><h3>数据与评价口径</h3><p>{people.length} 名人员、{roles.length} 类岗位、{db.tasks.length} 项任务、{capabilities.length} 项能力、{db.evidence.length} 条证据均为合成示例。业务数值、等级阈值和规则不代表正式制度。</p><p>按当前等级是否达到要求逐项判断；已确认达标项占比为达标项数除以适用项数，缺证单独展示，不代表能力零分。等级不换算能力分数，关键门槛不相互抵消。统一对标与个人成长目标分开，训练不会自动升星。</p><h3>参考附件</h3><ul><li>岗位能力图谱建设方案：最终版、领导汇报优化版、最终版副本</li><li>岗位能力墙建设方案汇报版（29页）</li><li>岗位能力墙建设方案 V2.8（文件名；封面版本 V2.6）</li></ul><h3>演示范围</h3><p>支持组织任职、体系版本、场景授权、评价复核、供需预案、业务诊断与人才梯队的模拟操作。操作保存于当前浏览器，刷新后继续；没有真实业务系统接入或多人协同后台。审批人与人员数据均为演示身份，正式评价制度及生产权限仍需接入。</p></div></DialogContent></Dialog>
 </SidebarProvider>
}
