'use client';
import { useState, useEffect, useRef } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, BriefcaseBusiness, Target, Database, ShieldCheck, Clock, FileText, GitBranch, BookOpen, Users, CircleCheck, X } from 'lucide-react';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { db, roles, roleById, personById, capById, targetsFor, peopleFor, personMetrics, statusLabel, statusTone, type Person, type EvidenceStatus } from './model';
import { Picker, Badge, DataTable, Note, Stars } from './ui-parts';
import type { DetailRef } from './graph-view';
import {rankLabel,registeredRankContext,jobFor,profileFor} from './foundation';
import {KnowledgeLinks} from './reference-panels';
import {PersonRoles} from './person-roles';
import {PersonCapabilityPlan} from './person-capability-plan-view';
import {PersonCapabilityRadar} from './person-capability-radar';
import {useManagement} from './management-context';
import {roleGrowthTarget} from './management-model';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {getRequirementDetail} from './requirement-detail';
import {handlingGuidance} from './requirement-guidance';

function objectTitle(d:DetailRef){return d.type==='person'?personById(d.id)?.name:d.type==='role'?roleById(d.id)?.name:d.type==='capability'?capById(d.id)?.name:d.type==='asset'?db.dataAssets.find(a=>a.id===d.id)?.name:d.type==='task'?db.tasks.find(t=>t.id===d.id)?.name:db.evidence.find(e=>e.id===d.id)?.name}

export function DetailPanel({stack,onClose,onBack,onDetail,onGrowth,onData}:{stack:DetailRef[];onClose:()=>void;onBack:()=>void;onDetail:(d:DetailRef)=>void;onGrowth:(p:Person)=>void;onData:(id:string,tab:string)=>void}){
 const d=stack[stack.length-1];const [level,setLevel]=useState('3');const [star,setStar]=useState('3');const requirementTitleRef=useRef<HTMLHeadingElement>(null);
 const {state:managementState}=useManagement();
 const [radarSelection,setRadarSelection]=useState<{personId:string;family:string|null}|null>(null);
 useEffect(()=>{setLevel(String(d?.level||3));setStar(String(d?.star||3))},[d?.id,d?.level,d?.star]);
 if(d?.type==='capability'&&d.mode==='requirement'){
  const capability=capById(d.id);const behavior=capability.levels.find(item=>item.level===d.level);
  const target=d.roleId?targetsFor(d.roleId,d.star).find(item=>item.capabilityId===d.id&&item.targetLevel===d.level):undefined;
  const detail=getRequirementDetail({capabilityId:d.id,roleId:d.roleId,level:d.level,star:d.star});
  const guidance=handlingGuidance(d.id,d.level);
  const checks=[...new Set(detail.tasks.map(task=>task.completionCriteria).filter(Boolean))];
  return <Dialog open onOpenChange={open=>{if(!open)onClose()}}><DialogContent className="capability-requirement-dialog" initialFocus={requirementTitleRef}>
   <DialogHeader><DialogTitle ref={requirementTitleRef} tabIndex={-1} className="requirement-dialog-title">{capability.name} · L{d.level}</DialogTitle><DialogDescription>{d.roleId?roleById(d.roleId).name:''}{d.star?` · ${d.star} 星能力对标`:''}{target?` · ${target.required?'必选要求':'发展要求'}`:''}</DialogDescription></DialogHeader>
   <div className="capability-requirement-scroll">
    <div className="capability-requirement-body"><span className="requirement-section-eyebrow">本级要求</span><h3>{behavior?.name||'能力要求'}</h3><p>{target?.behavior?.trim()||behavior?.behavior||'暂无对应等级的能力要求。'}</p><small>{capability.definition}</small></div>
    {guidance.length>0&&<section className="requirement-section"><h3><BookOpen size={16}/>具体怎么做<span>行为要求说明</span></h3><ol className="requirement-guidance">{guidance.map((text,index)=><li key={text}><span aria-hidden="true">{index+1}</span><p>{text}</p></li>)}</ol></section>}
    <div className="requirement-context-grid">
     <section className="requirement-section"><h3><BriefcaseBusiness size={16}/>适用业务</h3>{detail.scenarios.length?<div className="requirement-tags">{detail.scenarios.map(scene=><span key={scene.id}>{scene.name}</span>)}</div>:<p className="requirement-empty">当前岗位尚无明确的场景关联。</p>}</section>
     <section className="requirement-section"><h3><FileText size={16}/>可参考的材料</h3>{detail.evidenceTypes.length?<div className="requirement-tags muted">{detail.evidenceTypes.map(type=><span key={type}>{type}</span>)}</div>:<p className="requirement-empty">暂无匹配的材料类型。</p>}<small className="requirement-material-note">核验具体记录后，才能作为评价依据。</small></section>
    </div>
    {(checks.length>0||guidance.length>0)&&<section className="requirement-checks"><CircleCheck size={17}/><div><h3>做到什么程度</h3>{guidance.length>0?<><p>办理条件已核清，关键操作有记录，结果与反馈一致，后续责任明确。</p><small>对原行为要求的说明；具体评价仍按本级要求核验。</small></>:<>{checks.map(check=><p key={check}>{check}</p>)}<small>以上为关联任务的完成口径；能力等级仍按本级要求核验。</small></>}</div></section>}
    {detail.tasks.length>0&&<details className="requirement-task-details" open={guidance.length===0}><summary>{guidance.length?'查看关联办理任务':'具体业务中怎么做'}<span>{detail.totalTasks>detail.tasks.length?`展示 ${detail.tasks.length} / ${detail.totalTasks} 项`:`${detail.tasks.length} 项`}</span></summary><div>{detail.tasks.map(task=><article className="requirement-task" key={task.id}><h4>{task.name}</h4>{task.action!==task.name&&<p>{task.action}</p>}<p><span>完成后留下</span>{task.output}</p></article>)}</div></details>}
    <div className="requirement-source-note">{detail.notes.map(note=><p key={note}>{note}</p>)}{guidance.length>0&&<p>操作要点为说明性细化，不新增评分或必选门槛。</p>}</div>
   </div>
  </DialogContent></Dialog>;
 }
 return <Sheet open={!!d} onOpenChange={open=>{if(!open)onClose()}}><SheetContent className="detail-sheet" showCloseButton={false}><SheetHeader className="detail-header"><button type="button" className="detail-close" aria-label="关闭详情" onClick={onClose}><X size={18}/></button>{stack.length>1&&<button className="detail-back" onClick={onBack}><ArrowLeft size={15}/>返回{objectTitle(stack[stack.length-2])}</button>}<div className="eyebrow">{d?.type==='person'?'PERSONAL CAPABILITY':d?.type==='evidence'?'EVIDENCE TRACE':'ONTOLOGY DETAILS'}</div><SheetTitle>{d?objectTitle(d):'对象详情'}</SheetTitle><SheetDescription>{d?.id} · 业务、标准与数据关联详情 · 模拟数据</SheetDescription></SheetHeader>{d&&<div className="detail-content">
 {d.type==='person'&&(()=>{const p=personById(d.id);const targetStars=roleGrowthTarget(managementState,p.id,p.roleId);const m=targetStars===null?{score:null,known:0,total:0}:personMetrics(p,p.roleId,targetStars);const requestedFamily=radarSelection?.personId===p.id?radarSelection.family:null;const activeFamily=requestedFamily&&targetStars!==null&&targetsFor(p.roleId,targetStars).some(t=>capById(t.capabilityId).category===requestedFamily)?requestedFamily:null;const rawPerson=db.people.find(x=>x.id===p.id)!;return <><PersonRoles personId={p.id}/><div className="detail-section-heading"><h3>主岗能力画像</h3></div><div className="person-overview"><div><span className="avatar xlarge">{p.name}</span><h3>{roleById(p.roleId).name}</h3><p>{p.team}</p><div className="formal-stars"><Badge>{rankLabel(p.id,p.roleId)} · 本岗位登记（模拟）</Badge><small>{registeredRankContext(p.id,p.roleId)}</small><Badge tone="blue">{p.resultStatus}</Badge></div><div className="profile-kpi"><b>{m.score===null?'—':`${m.score}%`}</b><span>已确认达标项占比 · {targetStars===null?'本岗目标待确认':`目标 ${targetStars} 星`}</span><small>可判断 {m.known} / {m.total} 项能力</small></div></div><PersonCapabilityRadar person={p} targetStars={targetStars} activeFamily={activeFamily} onFamilyChange={family=>setRadarSelection({personId:p.id,family})}/></div><div className="record-meta"><span>结果版本 <b>{p.standardVersion}</b></span><span>评价周期 <b>{rawPerson.evaluationPeriod}</b></span><span>生效时间 <b>{rawPerson.resultEffectiveAt}</b></span><span>事实截止 <b>{rawPerson.factCutoffAt}</b></span></div><PersonCapabilityPlan person={p} targetStars={targetStars} activeFamily={activeFamily} onDetail={onDetail}/><button className="button primary full" onClick={()=>onGrowth(p)}>制定成长计划<ArrowRight size={16}/></button></>})()}
 {d.type==='role'&&(()=>{const r=roleById(d.id);const targets=targetsFor(r.id,Number(star));return <><div className="role-detail-hero"><span className="detail-symbol"><BriefcaseBusiness size={28}/></span><div><Badge>{db.businessDomains.find(x=>x.id===r.domainId)?.name}</Badge><p>{r.capabilityIds.length} 项能力 · {r.scenarioIds.length} 个场景 · {peopleFor(r.id).length} 名人员</p></div></div><Note>参考岗位：{jobFor(r.id)?.name||r.name} · {profileFor(r.id)?.coverage||'新增岗位标准待业务确认'}</Note><div className="detail-section-heading"><h3>岗位职责</h3><Badge tone="gray">岗位工作链</Badge></div><div className="responsibility-list">{db.responsibilities.filter(x=>r.responsibilityIds.includes(x.id)).map(x=><div key={x.id}><CircleCheck size={16}/><span>{x.name}</span></div>)}</div><div className="detail-section-heading"><h3>能力对标要求（图片五星标尺）</h3><Picker label="查看能力对标要求" value={star} onChange={setStar} options={[1,2,3,4,5].map(v=>({value:String(v),label:`${v} 星要求（演示）`}))}/></div><DataTable headers={['能力标准','目标等级','要求类型','标准版本']} rows={targets.map(t=>[<button className="text-button" onClick={()=>onDetail({type:'capability',id:t.capabilityId,level:t.targetLevel,roleId:r.id,star:Number(star)})}>{capById(t.capabilityId).name}<ArrowUpRight size={13}/></button>,`L${t.targetLevel}`,t.required?<Badge>必选</Badge>:<Badge tone="gray">发展</Badge>,t.standardVersion])}/><div className="detail-section-heading"><h3>在岗人员</h3><span>{peopleFor(r.id).length} 人</span></div><div className="people-chips">{peopleFor(r.id).map(p=><button key={p.id} onClick={()=>onDetail({type:'person',id:p.id})}><span className="avatar small">{p.name.slice(-1)}</span><b>{p.name}</b><small>{rankLabel(p.id,r.id)}</small><ArrowUpRight size={12}/></button>)}</div><Note>岗位能力对标要求为独立关联对象，将岗位、星级、能力、目标等级和必选条件连接起来。表中数值为演示口径。</Note></>})()}
 {d.type==='capability'&&(()=>{const c=capById(d.id);const behavior=c.levels.find(l=>l.level===Number(level))!;const contextual=d.roleId?targetsFor(d.roleId,d.star).find(t=>t.capabilityId===c.id):undefined;return <><div className="tag-list"><Badge>{c.category}</Badge><Badge tone="gray">{db.meta.standardVersion}</Badge><Badge tone="blue">演示已发布</Badge></div><p className="definition-text">{c.definition}</p>{d.roleId&&<div className="context-line">当前依据：{roleById(d.roleId).name} / {d.star} 星能力对标 / 目标 L{d.level}</div>}<div className="detail-section-heading"><h3>能力等级与行为标准</h3><Picker label="查看行为等级" value={level} onChange={setLevel} options={c.levels.map(l=>({value:String(l.level),label:`L${l.level} · ${l.name}`}))}/></div><div className="behavior-standard"><span>L{level}</span><div><h3>{behavior.name}</h3><p>{contextual?.behavior&&Number(level)===contextual.targetLevel?contextual.behavior:behavior.behavior}</p>{contextual?.behavior&&Number(level)===contextual.targetLevel&&<small>按当前岗位 × 对标要求细化；用户能力墙图片中的行为示例。</small>}<small>评价关注可观察行为，结合业务场景验证。</small></div></div><div className="detail-section-heading"><h3>横向关联岗位样本</h3><span>{c.roleIds.length} 类</span></div><div className="related-role-cards">{roles.filter(r=>r.capabilityIds.includes(c.id)).map(r=><button key={r.id} onClick={()=>onDetail({type:'role',id:r.id})}><BriefcaseBusiness size={17}/>{r.name}<ArrowUpRight size={14}/></button>)}</div><div className="detail-section-heading"><h3>业务中的应用</h3></div><div className="capability-task-summary">{db.businessDomains.map(domain=>{const tasks=db.tasks.filter(t=>t.capabilityIds.includes(c.id)&&t.scenarioIds.some(id=>db.scenarios.some(scene=>scene.id===id&&scene.domainId===domain.id)));return tasks.length?<p key={domain.id}><b>{domain.name}</b><span>{tasks.map(t=>t.name).join('；')}。</span></p>:null})}</div><div className="detail-section-heading"><h3>对应成长资源</h3></div>{db.growthResources.filter(r=>r.capabilityIds.includes(c.id)).map(r=><div className="resource-reference" key={r.id}><BookOpen size={18}/><div><b>{r.name}</b><p>{r.verification}</p></div></div>)}<Note>新能力与新等级需要定义行为、验证方式和适用岗位，经人工确认发布后才可用于评价。</Note></>})()}
 {d.type==='task'&&(()=>{const t=db.tasks.find(t=>t.id===d.id)!;return <><div className="tag-list">{db.scenarios.filter(s=>t.scenarioIds.includes(s.id)).map(s=><Badge tone="blue" key={s.id}>{s.name}</Badge>)}</div><div className="task-io">{[['输入',t.input],['办理动作',t.action],['输出',t.output]].map(([label,value])=><div key={label}><b>{label}</b><p>{value}</p></div>)}</div><h3 className="detail-section-heading">需要具备的能力</h3><div className="related-role-cards">{t.capabilityIds.map(id=><button key={id} onClick={()=>onDetail({type:'capability',id})}><Target size={17}/>{capById(id).name}<ArrowUpRight size={14}/></button>)}</div><h3 className="detail-section-heading">承担任务的岗位</h3><div className="detail-list">{roles.filter(r=>r.taskIds.includes(t.id)).map(r=><button key={r.id} onClick={()=>onDetail({type:'role',id:r.id})}><BriefcaseBusiness size={17}/>{r.name}<ArrowRight size={14}/></button>)}</div><KnowledgeLinks taskId={t.id}/><Note>任务是业务架构与能力标准的连接点，输入、动作和输出用于明确具体履职场景。</Note></>})()}
 {d.type==='evidence'&&(()=>{const e=db.evidence.find(e=>e.id===d.id)!;const asset=db.dataAssets.find(a=>a.id===e.assetId)!;return <><div className="tag-list"><Badge tone={statusTone[e.evidenceStatus as EvidenceStatus]}>{statusLabel[e.evidenceStatus as EvidenceStatus]}</Badge><Badge tone="blue">{e.type} · 合成记录包</Badge><Badge>记录质量通过</Badge></div><p className="definition-text">{e.summary}</p><div className="record-meta"><span>人员 <button onClick={()=>onDetail({type:'person',id:e.employeeId})}>{personById(e.employeeId).name}<ArrowUpRight size={12}/></button></span><span>源记录 <b>{e.sourceRecordId}</b></span><span>观察时点 <b>{e.observedAt}</b></span><span>有效期限 <b>{e.validUntil}</b></span><span>标准版本 <b>{e.standardVersion}</b></span><span>规则版本 <b>{e.ruleVersion}</b></span><span>采集批次 <b>{e.batchId}</b></span><span>责任专业 <b>{e.owner}</b></span></div>{e.evidenceStatus!=='admissible'&&<Note>该记录当前为“{statusLabel[e.evidenceStatus as EvidenceStatus]}”，不可用于本次新的能力结论。保留来源与历史观察，不将其转成零分。</Note>}<h3 className="detail-section-heading">行为观察明细</h3><DataTable headers={['能力','观察等级','行为标准编码','结果']} rows={e.observations.map(o=>[<button className="text-button" onClick={()=>onDetail({type:'capability',id:o.capabilityId,level:o.level})}>{capById(o.capabilityId).name}</button>,`L${o.level}`,<div>{o.behaviorId}{o.roleBehavior&&<small className="cell-note">{o.roleBehavior}</small>}</div>,o.result])}/><KnowledgeLinks evidenceId={e.id}/><div className="evidence-source"><Database size={24}/><div><h3>{asset.name}</h3><p>{asset.system} / {asset.tableName}</p></div></div><button className="button primary full" onClick={()=>onData(asset.id,'lineage')}><GitBranch size={17}/>继续追溯数据血缘<ArrowRight size={16}/></button><Note>这里展示合成记录包及逐项观察，方便原型追溯。实际建设中应回到真实原始记录，并按证据类型、样本量和有效期确定可采信用途。</Note></>})()}
 {d.type==='asset'&&(()=>{const a=db.dataAssets.find(a=>a.id===d.id)!;return <><div className="tag-list"><Badge tone={a.qualityStatus==='passed'?'green':'amber'}>{a.qualityStatus==='passed'?'源端质量通过':'存在源端待处理问题'}</Badge><Badge tone="blue">{a.authorization}</Badge></div><p className="definition-text">{a.evidencePurpose}</p><div className="record-meta"><span>源系统 <b>{a.system}</b></span><span>责任专业 <b>{a.owner}</b></span><span>更新频率 <b>{a.refreshFrequency}</b></span><span>最近更新 <b>{a.updatedAt}</b></span><span>质量评分 <b>{a.qualityScore} / 100（模拟）</b></span><span>待处理问题 <b>{a.openIssues} 项</b></span></div><h3 className="detail-section-heading">质量校验规则</h3><DataTable headers={['规则编码','规则','维度','状态']} rows={a.qualityRules.map(r=>[r.id,r.name,r.dimension,<Badge tone={r.status==='passed'?'green':'amber'}>{r.status==='passed'?'通过':'待整改'}</Badge>])}/><h3 className="detail-section-heading">字段与业务标准</h3><DataTable headers={['源字段','业务名称','匹配标准']} rows={a.fields.map(f=>[<code>{f.name}</code>,f.label,f.standard.name])}/><div className="tag-list section-gap">{a.tags.map(t=><Badge key={t.id} tone="gray">{t.name}</Badge>)}</div><button className="button primary full section-gap" onClick={()=>onData(a.id,'catalog')}>进入数据治理<ArrowRight size={15}/></button>{a.openIssues>0&&<Note>未通过的源端记录需要责任专业整改并复验。质量问题不会自动扣减人员能力等级，已采信证据与待接入数据分别管理。</Note>}</>})()}
 </div>}</SheetContent></Sheet>
}
