'use client';
import { useState, useEffect } from 'react';
import { TrendingUp, ArrowRight, ArrowUpRight, BookOpen, CircleCheck, Clock, ListChecks, Target, Plus, GraduationCap, MoveHorizontal, ShieldCheck } from 'lucide-react';
import { db, roles, people, personById, roleById, capById, targetsFor, gapFor, personMetrics, type Person } from './model';
import { Picker, Badge, DataTable, PanelTitle, Note, Stars } from './ui-parts';
import type { DetailRef } from './graph-view';

export type GrowthPlan={personId:string;resourceId:string;status:'planned'|'trained'|'review'};
export function GrowthView({personId,setPersonId,plans,setPlans,onDetail,onNotice}:{personId:string;setPersonId:(id:string)=>void;plans:GrowthPlan[];setPlans:(p:GrowthPlan[])=>void;onDetail:(d:DetailRef)=>void;onNotice:(s:string)=>void}){
 const p=personById(personId);const [targetRole,setTargetRole]=useState(p.roleId);const [star,setStar]=useState(String(p.targetStars));
 useEffect(()=>{const next=personById(personId);setTargetRole(next.roleId);setStar(String(next.targetStars))},[personId]);
 const ts=targetsFor(targetRole,Number(star));const m=personMetrics(p,targetRole,Number(star));const deficits=ts.filter(t=>gapFor(p,t.capabilityId,t.targetLevel).label!=='已达目标');const capIds=deficits.map(t=>t.capabilityId);const resources=db.growthResources.filter(r=>r.capabilityIds.some(id=>capIds.includes(id))).sort((a,b)=>Number(b.capabilityIds.includes(p.growthFocus.capabilityId))-Number(a.capabilityIds.includes(p.growthFocus.capabilityId)));
 const personPlans=plans.filter(x=>x.personId===personId);
 const add=(resourceId:string)=>{if(plans.some(x=>x.personId===personId&&x.resourceId===resourceId))return;setPlans([...plans,{personId,resourceId,status:'planned'}]);onNotice(`已为${p.name}加入成长计划，仅保存在本次演示。`)};
 const advance=(resourceId:string,status:GrowthPlan['status'])=>{setPlans(plans.map(x=>x.personId===personId&&x.resourceId===resourceId?{...x,status}:x));onNotice(status==='trained'?'训练完成已记录。完成训练不等于能力达标，请按行为要求提交复测。':'已提交模拟复测，状态为待复核。原星级与已生效能力结果保持不变。')};
 return <><section className="panel"><PanelTitle title="让每个人看清下一步" sub="对照岗位标尺，区分能力差距与证据缺口，形成有验证方式的成长计划" icon={<TrendingUp size={18}/> }><Picker label="选择成长人员" value={personId} onChange={setPersonId} options={people.map(x=>({value:x.id,label:`${x.name} · ${x.team}`}))}/></PanelTitle><div className="growth-profile"><div className="profile-identity"><span className="avatar large">{p.name}</span><div><h2>{p.name}</h2><p>{roleById(p.roleId).name} · {p.team}</p><Stars value={p.formalStars}/><span className="muted">当前 {p.formalStars} 星 · 模拟已生效</span></div></div><div className="growth-target"><MoveHorizontal size={24}/><label>目标岗位<Picker label="成长目标岗位" value={targetRole} onChange={setTargetRole} options={roles.map(r=>({value:r.id,label:r.name}))}/></label><label>目标星级<Picker label="成长目标星级" value={star} onChange={setStar} options={[1,2,3,4,5].map(v=>({value:String(v),label:`${v} 星要求`}))}/></label></div></div><div className="growth-snapshot"><span><CircleCheck size={17}/><b>{m.achieved}</b> 项已达目标</span><span><Target size={17}/><b>{m.known-m.achieved}</b> 项能力差距</span><span><Clock size={17}/><b>{m.unknown}</b> 项需补证 / 复核</span><Badge tone="blue">{targetRole===p.roleId?'纵向进阶':'横向跨岗发展'}</Badge></div><DataTable headers={['目标能力','当前记录','目标要求','差距判断','推荐行动','依据']} rows={ts.map(t=>{const v=p.capabilities[t.capabilityId];const gap=gapFor(p,t.capabilityId,t.targetLevel);return [<button className="text-button" onClick={()=>onDetail({type:'capability',id:t.capabilityId})}>{capById(t.capabilityId).name}</button>,v?.level!==null&&v?.level!==undefined?<span>L{v.level}{v.evidenceStatus!=='admissible'&&<small className="cell-note">历史记录，当前不可采信</small>}</span>:<Badge tone="gray">未形成有效记录</Badge>,<div><b>L{t.targetLevel}</b><small className="cell-note">{t.required?'必选能力':'发展能力'}</small></div>,<Badge tone={gap.tone}>{gap.label}</Badge>,<span className="wrap-cell">{gap.label==='已达目标'?'保持实践，按周期更新证据':gap.label==='能力差距'?'针对目标行为开展训练与复测':gap.description}</span>,v?.evidenceIds.length?<button className="text-button" onClick={()=>onDetail({type:'evidence',id:v.evidenceIds[0]})}>证据记录<ArrowUpRight size={14}/></button>:<span className="muted">需补充有效证据</span>]})}/></section>
 <div className="section-title"><div><h2>针对差距的成长资源</h2><p>每项资源关联能力、业务场景与复测方法</p></div><Badge tone="gray">{resources.length} 项匹配资源</Badge></div><div className="resource-grid">{resources.map(r=>{const added=plans.some(x=>x.personId===personId&&x.resourceId===r.id);return <article className="resource-card" key={r.id}><div className="resource-top"><span className="resource-icon"><BookOpen size={24}/></span><Badge tone="blue">{r.type}</Badge><small>{r.durationMinutes} 分钟</small></div><h3>{r.name}</h3><div className="tag-list">{r.capabilityIds.map(id=><Badge key={id}>{capById(id).name}</Badge>)}</div><p>{r.reason}</p><div className="verification"><ShieldCheck size={15}/><div><b>如何验证</b><span>{r.verification}</span></div></div><button className={`button full ${added?'outline':'primary'}`} onClick={()=>add(r.id)} disabled={added}>{added?<><CircleCheck size={15}/>已加入本次计划</>:<><Plus size={15}/>加入成长计划</>}</button></article>})}{!resources.length&&<div className="empty-state"><CircleCheck size={30}/><b>当前可判断能力已达到所选目标</b><span>可选择更高要求或其他岗位继续探索成长方向。</span></div>}</div>
 <section className="panel section-gap"><PanelTitle title={`${p.name}的成长计划`} sub="计划 → 训练 → 复测 → 人工复核 → 评价结果回流" icon={<ListChecks size={18}/> }><Badge tone="gray">仅本次演示保存</Badge></PanelTitle>{personPlans.length?<DataTable headers={['成长任务','目标能力','当前阶段','下一步']} rows={personPlans.map(x=>{const r=db.growthResources.find(r=>r.id===x.resourceId)!;return [r.name,r.capabilityIds.map(id=>capById(id).name).join(' / '),<Badge tone={x.status==='review'?'blue':x.status==='trained'?'green':'amber'}>{x.status==='planned'?'待训练':x.status==='trained'?'训练完成，待复测':'复测已提交，待复核'}</Badge>,x.status==='planned'?<button className="button outline" onClick={()=>advance(x.resourceId,'trained')}>标记训练完成<CircleCheck size={14}/></button>:x.status==='trained'?<button className="button primary" onClick={()=>advance(x.resourceId,'review')}>提交模拟复测<ArrowRight size={14}/></button>:<span className="muted">等待授权评价人员复核</span>]})}/>:<div className="empty-state"><GraduationCap size={34}/><b>尚未安排成长任务</b><span>从上方资源加入计划，开始演示训练与复测流程。</span></div>}<Note>训练完成仅新增过程状态；复测提交后仍需采信、规则测算和人工复核。本原型不执行正式升星、不写入真实人员系统，刷新页面会重置演示计划。</Note></section></>
}
