'use client';
import {useState} from 'react';
import {Upload,Download,Plus,Workflow} from 'lucide-react';
import {useManagement} from './management-context';
import {nameOf,uid,addAudit,currentVersion,type Handoff} from './management-model';
import {exampleHandoffs} from './workflow-model';
import {previewBatch,applyBatch,checkHandoffs} from './template-model';
import {exportCsv} from './model';
import {Picker,Badge,PanelTitle,DataTable,Note} from './ui-parts';
import {Field,TextField,Modal,Actions} from './management-ui';
import {Checkbox} from '@/components/ui/checkbox';

export function HandoffView({editable=false,roleId}:{editable?:boolean;roleId?:string}){
 const {state:s,mutate}=useManagement();const c=editable?(s.draft?.catalog||s.catalog):s.catalog;const [edit,setEdit]=useState<Handoff|null>(null);const nodes=(kind:string)=>c.nodes.filter(n=>n.kind===kind&&n.active);const label=(id:string)=>c.nodes.find(n=>n.id===id)?.name||id;
 const records=(c.handoffs||[]).filter(h=>!roleId||[h.leadRoleId,...h.supportRoleIds,h.reviewRoleId,h.escalateRoleId].includes(roleId));const canEdit=editable&&(!s.draft||s.draft.status==='草稿');
 const ensureDraft=(st:typeof s)=>{if(!st.draft)st.draft={catalog:structuredClone(st.catalog),policies:structuredClone(st.policies),status:'草稿',reviewer:'',note:'完善跨岗位协同责任与交接标准',date:st.date};if(st.draft.status!=='草稿')throw new Error('草稿已进入审核，暂不可修改');st.draft.catalog.handoffs??=[];return st.draft.catalog};
 return <section className="panel"><PanelTitle title="跨岗位协同责任标准" sub={`${editable&&s.draft?'当前维护草稿':'当前已发布标准'} · 一个场景任务对应一条责任与交接约定`} icon={<Workflow size={18}/> }>{editable&&<Actions><button disabled={!canEdit} className="button outline" onClick={()=>mutate(st=>{const c=ensureDraft(st);let count=0;for(const h of exampleHandoffs(c)){if(!c.handoffs!.some(x=>x.scenarioId===h.scenarioId&&x.taskId===h.taskId)){c.handoffs!.push(h);count++}}if(!count)throw new Error('演示模板已存在，无需重复载入');addAudit(st,'载入协同标准模板',`${count} 项；须审核发布`)})}>载入两项演示模板</button><button disabled={!canEdit} className="button primary" onClick={()=>setEdit({id:uid('HANDOFF'),scenarioId:'SCN-05',taskId:'TASK-14',leadRoleId:'ROLE-03',supportRoleIds:['ROLE-02'],reviewRoleId:'ROLE-04',escalateRoleId:'ROLE-06',materials:'',acceptance:'',deadlineHours:2,escalation:'',owner:'投诉处置专业'})}><Plus size={15}/>新增约定</button></Actions>}</PanelTitle><DataTable headers={['场景 / 任务','主办与协办','复核 / 升级岗位','交接材料与接收条件','时限与升级条件',...(editable?['维护']:[])]} rows={records.map(h=>[<div><b>{label(h.scenarioId)}</b><small className="cell-note">{label(h.taskId)}</small></div>,<div><Badge>{label(h.leadRoleId)} · 主办</Badge><small className="cell-note">协办：{h.supportRoleIds.map(label).join('、')||'无'}</small></div>,<div>{label(h.reviewRoleId)}<small className="cell-note">升级至 {label(h.escalateRoleId)}</small></div>,<div className="mg-definition">{h.materials}<small className="cell-note">接收条件：{h.acceptance}</small></div>,<div className="mg-definition">{h.deadlineHours} 小时<small className="cell-note">{h.escalation}</small></div>,...(editable?[<button disabled={!canEdit} className="text-button" onClick={()=>setEdit(structuredClone(h))}>编辑</button>]:[])])} empty={editable?'尚未维护协同约定，可载入演示模板后审核发布':'该版本尚未发布本岗位协同约定'}/><Note>同一任务在不同场景可有不同分工。协同约定与业务标准一起审核、发布和追溯；主办、协办和复核职责不自动合并为每个人的能力要求。</Note>
 <Modal open={!!edit} onClose={()=>setEdit(null)} title="维护协同责任与交接要求" sub="保存到体系草稿，完成统一校验与审核后生效。">{edit&&<><div className="mg-form-grid"><label className="mg-field"><span>业务场景</span><Picker label="协同业务场景" value={edit.scenarioId} onChange={scenarioId=>setEdit({...edit,scenarioId,taskId:c.edges.find(e=>e.type==='scenarioTask'&&e.from===scenarioId)?.to||''})} options={nodes('scenario').map(n=>({value:n.id,label:n.name}))}/></label><label className="mg-field"><span>具体任务</span><Picker label="协同具体任务" value={edit.taskId} onChange={taskId=>setEdit({...edit,taskId})} options={c.edges.filter(e=>e.type==='scenarioTask'&&e.from===edit.scenarioId).map(e=>({value:e.to,label:label(e.to)}))}/></label>{([['主办岗位','leadRoleId'],['复核岗位','reviewRoleId'],['升级岗位','escalateRoleId']] as const).map(([title,key])=><label key={key} className="mg-field"><span>{title}</span><Picker label={title} value={edit[key]} onChange={value=>setEdit({...edit,[key]:value})} options={nodes('role').map(n=>({value:n.id,label:n.name}))}/></label>)}<Field label="反馈时限（小时）" type="number" min="0.25" step="0.25" value={edit.deadlineHours} onChange={e=>setEdit({...edit,deadlineHours:Number(e.target.value)})}/></div><div className="v3-checkboxes"><b>协办岗位</b>{nodes('role').filter(n=>n.id!==edit.leadRoleId).map(n=><label key={n.id}><Checkbox checked={edit.supportRoleIds.includes(n.id)} onCheckedChange={yes=>setEdit({...edit,supportRoleIds:yes?[...edit.supportRoleIds,n.id]:edit.supportRoleIds.filter(id=>id!==n.id)})}/>{n.name}</label>)}</div><TextField label="必需交接材料" value={edit.materials} onChange={materials=>setEdit({...edit,materials})}/><TextField label="接收与完成条件" value={edit.acceptance} onChange={acceptance=>setEdit({...edit,acceptance})}/><TextField label="异常或超时升级条件" value={edit.escalation} onChange={escalation=>setEdit({...edit,escalation})}/><Field label="责任专业或维护人" value={edit.owner} onChange={e=>setEdit({...edit,owner:e.target.value})}/><Actions><button className="button primary" onClick={()=>{if(mutate(st=>{const c=ensureDraft(st);const next={...c,handoffs:[...(c.handoffs||[]).filter(h=>h.id!==edit.id),edit]};const errors=checkHandoffs(next);if(errors.length)throw new Error(errors[0]);c.handoffs=next.handoffs;addAudit(st,'维护协同责任草稿',`${edit.scenarioId} / ${edit.taskId}`)}))setEdit(null)}}>保存协同约定</button></Actions></>}</Modal></section>;
}
export function TemplateView(){
 const {state:s,mutate,notify}=useManagement();const [type,setType]=useState('场景'),[source,setSource]=useState('SCN-03'),[newId,setNewId]=useState('SCN-NEW-01'),[name,setName]=useState('重大停电解释与反馈'),[owner,setOwner]=useState('业务运营专业');
 const [text,setText]=useState('类型,模板编码,新编码,新名称,负责人\n场景,SCN-03,SCN-NEW-01,重大停电解释与反馈,业务运营专业\n场景,SCN-05,SCN-NEW-02,跨专业诉求协同,投诉处置专业');const [preview,setPreview]=useState<ReturnType<typeof previewBatch>|null>(null);const [previewText,setPreviewText]=useState('');const [fileName,setFileName]=useState('');
 const c=s.draft?.catalog||s.catalog;const download=()=>exportCsv('岗位场景批量模板.csv',['类型','模板编码','新编码','新名称','负责人'],[['场景','SCN-03','SCN-NEW-01','重大停电解释与反馈','业务运营专业'],['岗位','ROLE-02','ROLE-NEW-01','故障支撑后备岗','报修服务专业']]);
 const validate=()=>{setPreview(previewBatch(s,text));setPreviewText(text)};
 return <><section className="panel"><PanelTitle title="模板与批量维护" sub="复用已发布对象及标准，整批校验后合入草稿"/><div className="mg-inset"><div className="mg-form-grid"><Picker label="新增对象类型" value={type} onChange={v=>{setType(v);setSource(v==='场景'?'SCN-03':'ROLE-02');setNewId(v==='场景'?'SCN-NEW-01':'ROLE-NEW-01')}} options={['场景','岗位'].map(v=>({value:v,label:v}))}/><Picker label="复用模板" value={source} onChange={setSource} options={c.nodes.filter(n=>n.kind===(type==='场景'?'scenario':'role')&&n.active).map(n=>({value:n.id,label:`${n.name} · ${n.id}`}))}/><Field label="新对象编码" value={newId} onChange={e=>setNewId(e.target.value)}/><Field label="新对象名称" value={name} onChange={e=>setName(e.target.value)}/><Field label="责任专业或维护人" value={owner} onChange={e=>setOwner(e.target.value)}/></div><Actions><button className="button outline" onClick={()=>{const row=[type,source,newId,name,owner].map(v=>'"'+v.replaceAll('"','""')+'"').join(',');setText(text.trim()+'\n'+row);setPreview(null)}}><Plus size={15}/>加入下方待导入清单</button><button className="button outline" onClick={download}><Download size={15}/>下载填写模板</button><label className="button outline v3-file-button"><Upload size={15}/>读取 CSV 文件<input type="file" accept=".csv,text/csv" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>200000)throw new Error('请使用 200 KB 以内的 CSV 文件');setText((await file.text()).replace(/^\uFEFF/,''));setFileName(file.name);setPreview(null)}catch(err){notify((err as Error).message)}e.target.value=''}}/></label>{fileName&&<Badge tone="gray">{fileName}</Badge>}</Actions><TextField label="待导入清单（支持从模板填写后粘贴，每批最多 50 行）" value={text} onChange={v=>{setText(v);setPreview(null)}}/><Actions><button className="button primary" onClick={validate}>预览并校验整批内容</button></Actions></div><Note>场景模板复用原岗位、任务与能力，复制常规场景门槛；岗位模板复制职责结构及一至五星要求。专门的专家授权规则需另行配置。所有继承要求均须在草稿中确认后审核发布。</Note></section>
 {preview&&<section className="panel section-gap"><PanelTitle title="导入预览" sub={`基础版本 ${currentVersion(s)} · ${preview.summary.length} 行可解析内容`}><Badge tone={preview.errors.length?'amber':'green'}>{preview.errors.length?`${preview.errors.length} 项错误，整批未导入`:'结构检查通过'}</Badge></PanelTitle><DataTable headers={['行号','新增名称','类型','新增对象数','复用关系数','新增场景规则数']} rows={preview.summary.map(r=>[r.row,r.name,r.kind,r.added,r.reused,r.policies])}/>{preview.errors.length>0&&<div className="mg-inset v3-errors">{preview.errors.map(e=><p key={e}>{e}</p>)}</div>}<div className="mg-inset"><button disabled={!!preview.errors.length} className="button primary" onClick={()=>{if(mutate(st=>applyBatch(st,previewText,preview.stamp)))setPreview(null)}}>确认合入草稿，进入标准审核</button></div><Note>只写入草稿。预览后若标准或草稿变化，需要重新校验；相同编码再次导入会被阻止。</Note></section>}</>;
}
