'use client';
import {useState} from 'react';
import {Users,ArrowRight,ArrowUpRight,TriangleAlert,ChartNoAxesCombined,Plus,Route,Target} from 'lucide-react';
import {useManagement} from './management-context';
import {base,nameOf,prepareAllocation,supply,authorizationStatus,validateAllocation,uid,addAudit,type Allocation,type ActionItem} from './management-model';
import {Picker,Badge,DataTable,PanelTitle,Note,Segments} from './ui-parts';
import {Field,TextField,Modal,KPI,Actions} from './management-ui';
import type {DetailRef} from './graph-view';

export function SupplyView({onNavigate,onPerson}:{onNavigate:(p:string)=>void;onPerson:(id:string)=>void}){
 const {state:s,mutate}=useManagement();const [slotId,setSlotId]=useState('SLOT-1');const [policyId,setPolicyId]=useState('POL-SCN-03');const [team,setTeam]=useState('all');const [movePerson,setMovePerson]=useState('DEMO-018');const [moveTo,setMoveTo]=useState('POL-SCN-05');const [preview,setPreview]=useState<Allocation|null>(null);const [modal,setModal]=useState('');const [need,setNeed]=useState('3');const [demandTeam,setDemandTeam]=useState('报修一班');
 const policy=s.policies.find(p=>p.id===policyId)!;const allPolicyIds=[...new Set(s.demands.filter(d=>d.slotId===slotId).map(d=>d.policyId))];const policyIds=team==='all'?allPolicyIds:allPolicyIds.filter(id=>s.demands.some(d=>d.policyId===id&&d.slotId===slotId&&d.team===team));
 const projected=preview?[...s.allocations.filter(a=>a.personId!==preview.personId||a.slotId!==preview.slotId),preview]:s.allocations;
 const stats=policyIds.map(id=>({id,...supply(s,id,slotId,s.allocations,team)}));const detail=supply(s,policyId,slotId,s.allocations,team);const total=stats.reduce((n,x)=>n+x.demand,0);const assignedUnique=new Set(stats.flatMap(x=>x.assigned.map(p=>p.id))).size;const gap=stats.reduce((n,x)=>n+x.gap,0);
 const experts=supply(s,'POL-EXPERT',slotId).eligible;const covering=experts.filter(p=>projected.some(a=>a.personId===p.id&&a.slotId===slotId&&s.policies.find(x=>x.id===a.policyId)?.roleId==='ROLE-02'));
 const makePreview=()=>{const a=prepareAllocation(s,{personId:movePerson,policyId:moveTo,slotId});const error=validateAllocation(s,a,true);if(error){mutate(()=>{throw new Error(error)});return;}setPreview(a)};
 return <><KPI items={[{label:'本时段需求',value:total,note:'主管设定的同时独立在岗人数'},{label:'实际独立供给',value:assignedUnique,note:'每人每时段最多计入一项安排'},{label:'场景缺口',value:gap,note:'各场景缺口分别计算，不相互抵消'},{label:'高级故障研判覆盖',value:`${covering.length} 人`,note:covering.length<=1?'关键能力集中，需培养后备':'查看符合条件人员'}]}/><section className="panel"><PanelTitle title="组织能力供需与风险预警" sub="候选、授权、可用与实际安排分别统计；支援前检查原班组影响。" icon={<Users size={18}/> }><Actions><Picker label="供需时段" value={slotId} onChange={v=>{setSlotId(v);setPreview(null)}} options={s.slots.map(x=>({value:x.id,label:x.name}))}/><Picker label="供需班组" value={team} onChange={v=>{setTeam(v);const id=s.demands.find(d=>v==='all'||d.team===v)?.policyId;if(id)setPolicyId(id)}} options={[{value:'all',label:'全中心 / 按场景汇总'},...[...new Set(s.demands.map(d=>d.team))].map(v=>({value:v,label:v}))]}/></Actions></PanelTitle><DataTable headers={['业务场景','管理需求','能力与证据符合','独立授权有效','实际安排 / 缺口','风险','查看']} rows={stats.map(x=>[s.policies.find(p=>p.id===x.id)!.name,`${x.demand} 人`,`${x.qualified.length} 人`,`${x.authorized.length} 人`,<span><b>{x.assigned.length} 人</b> / 缺 {x.gap} 人</span>,<Badge tone={x.gap?'amber':'green'}>{x.gap?'保障缺口':x.free.length?'有后备可用':'已覆盖，后备不足'}</Badge>,<button className="text-button" onClick={()=>setPolicyId(x.id)}>人员名单</button>])}/><div className="mg-toolbar"><Badge tone="blue">{s.date} · {s.slots.find(x=>x.id===slotId)?.name}</Badge><button className="button outline" onClick={()=>setModal('demand')}>调整场景班组需求</button></div><Note>需求来自模拟管理设定，可用状态来自演示安排。班组视图按该场景适用任职归属统计；兼岗人员进入多个候选池，但每个时段只占用一次。</Note></section>
 <div className="mg-two-cols section-gap"><section className="panel"><PanelTitle title="跨岗支援预案" sub="先比较前后缺口，再确认调整。" icon={<Route size={18}/>}/><div className="mg-inset"><label className="mg-field"><span>支援人员</span><Picker label="支援人员" value={movePerson} onChange={v=>{setMovePerson(v);setPreview(null)}} options={base.people.map(p=>({value:p.id,label:p.name}))}/></label><label className="mg-field"><span>目标场景</span><Picker label="支援目标场景" value={moveTo} onChange={v=>{setMoveTo(v);setPreview(null)}} options={s.policies.map(p=>({value:p.id,label:p.name}))}/></label><Actions><button className="button primary" onClick={makePreview}>模拟调配影响</button>{preview&&<button className="button outline" onClick={()=>setPreview(null)}>撤销预案</button>}</Actions>{preview&&<><DataTable headers={['场景','调整前','调整后']} rows={allPolicyIds.map(id=>{const before=supply(s,id,slotId);const after=supply(s,id,slotId,projected);return [s.policies.find(p=>p.id===id)!.name,`${before.assigned.length}/${before.demand}，缺${before.gap}`,`${after.assigned.length}/${after.demand}，缺${after.gap}`]})}/><Note>预案为同一时段替换安排。总人数不会增加；其他场景的缺口可能随之变化。</Note><button className="button primary" onClick={()=>mutate(st=>{const error=validateAllocation(st,preview,true);if(error)throw new Error(error);st.allocations=st.allocations.filter(a=>a.personId!==preview.personId||a.slotId!==preview.slotId);st.allocations.push(preview);addAudit(st,'确认支援安排',`${nameOf(st,preview.personId)} → ${st.policies.find(p=>p.id===preview.policyId)!.name} / ${st.slots.find(x=>x.id===preview.slotId)!.name}`);setPreview(null)})}>确认此时段支援安排</button></>}</div></section><section className="panel"><PanelTitle title="关键能力与后备风险" sub="高级故障研判：故障研判 L5、安全风险识别 L4" icon={<TriangleAlert size={18}/>}/><div className="mg-inset"><div className="mg-risk-callout"><b>{experts.length} 名可用人员符合高级场景授权</b><p>{experts.map(p=>p.name).join('、')||'暂无可用人员'}；当前预案中保留在报修相关业务 {covering.length} 人。</p></div><h3 className="mg-section-label">正在培养的后备人员</h3>{s.development.filter(d=>d.targetPolicyId==='POL-EXPERT').map(d=><div className="mg-list-row" key={d.id}><b>{nameOf(s,d.personId)}</b><Badge tone="blue">{d.status}</Badge><span>导师：{nameOf(s,d.mentorId)}</span></div>)}<Note>后备培养人数不计入当前独立供给。抽调唯一符合者后，该项能力可能失去当班覆盖。</Note><button className="button outline" onClick={()=>onNavigate('talent')}>查看人才梯队<ArrowUpRight size={14}/></button></div></section></div>
 <section className="panel section-gap"><PanelTitle title={`${policy.name} · 人员供给明细`} sub="可用的授权候选与本时段占用状态"/><DataTable headers={['人员','独立授权','当班状态','当前安排','操作']} rows={base.people.filter(p=>detail.authorized.some(x=>x.id===p.id)||s.allocations.some(a=>a.personId===p.id&&a.policyId===policyId&&a.slotId===slotId)).map(p=>{const status=authorizationStatus(s,p.id,policyId);const unavailable=s.unavailable.includes(`${slotId}:${p.id}`);const allocation=s.allocations.find(a=>a.personId===p.id&&a.slotId===slotId);return [p.name,<Badge tone={status.tone}>{status.label}</Badge>,unavailable?'此时段不可用':'可用',allocation?s.policies.find(x=>x.id===allocation.policyId)?.name:'未安排',<Actions><button className="text-button" onClick={()=>mutate(st=>{const key=`${slotId}:${p.id}`;st.unavailable=unavailable?st.unavailable.filter(x=>x!==key):[...st.unavailable,key];addAudit(st,'调整时段可用状态',`${p.name} / ${slotId}`)})}>{unavailable?'设为可用':'设为不可用'}</button>{!allocation&&<button className="text-button" onClick={()=>mutate(st=>{const a={personId:p.id,policyId,slotId};const error=validateAllocation(st,a);if(error)throw new Error(error);st.allocations.push(prepareAllocation(st,a));addAudit(st,'安排当班场景',`${p.name} / ${policy.name}`)})}>安排此场景</button>}{allocation&&<button className="text-button" onClick={()=>mutate(st=>{st.allocations=st.allocations.filter(a=>a.personId!==p.id||a.slotId!==slotId);addAudit(st,'撤下时段安排',`${p.name} / ${slotId}`)})}>撤下安排</button>}<button className="text-button" onClick={()=>{onPerson(p.id);onNavigate('authorization')}}>授权详情</button></Actions>]})}/></section>
 <Modal open={modal==='demand'} onClose={()=>setModal('')} title="调整场景与班组需求" sub="输入该时段需要同时独立承担业务的人数，保留管理设定来源。"><Picker label="需求业务场景" value={policyId} onChange={setPolicyId} options={s.policies.map(p=>({value:p.id,label:p.name}))}/><Picker label="需求班组" value={demandTeam} onChange={setDemandTeam} options={s.orgs.filter(o=>o.type==='班组').map(o=>({value:o.name,label:o.name}))}/><Field label="独立在岗需求人数" type="number" min="0" step="1" value={need} onChange={e=>setNeed(e.target.value)}/><Actions><button className="button primary" onClick={()=>mutate(st=>{if(!Number.isInteger(Number(need))||Number(need)<0)throw new Error('需求须为非负整数');if(!st.positions.some(p=>p.roleId===policyId.replace('POL-','ROLE-')||p.roleId===st.policies.find(p=>p.id===policyId)?.roleId&&nameOf(st,p.orgId)===demandTeam))throw new Error('该班组未配置此场景适用岗位');const d=st.demands.find(d=>d.policyId===policyId&&d.slotId===slotId&&d.team===demandTeam);if(d)d.needed=Number(need);else st.demands.push({policyId,slotId,team:demandTeam,needed:Number(need)});addAudit(st,'调整管理需求',`${policy.name} / ${demandTeam} / ${need} 人`);setModal('')})}>保存需求</button></Actions></Modal></>;
}

export function DiagnosisView({onDetail,onNavigate}:{onDetail:(d:DetailRef)=>void;onNavigate:(p:string)=>void}){
 const {state:s,mutate}=useManagement();const [selected,setSelected]=useState('DIAG-01');const [cause,setCause]=useState('');const [modal,setModal]=useState('');const [title,setTitle]=useState('');const [owner,setOwner]=useState('DEMO-035');const [due,setDue]=useState('2026-09-12');const [acceptance,setAcceptance]=useState('');const [deliverable,setDeliverable]=useState('');const [actionId,setActionId]=useState('');const [scope,setScope]=useState('diagnosis');
 const d=s.diagnoses.find(x=>x.id===selected)!;const rate=([n,total]:[number,number])=>n/total*100;const delta=rate(d.current)-rate(d.before);const actions=s.actions.filter(a=>scope==='all'||a.diagnosisId===d.id);const action=s.actions.find(a=>a.id===actionId);
 return <><KPI items={[{label:d.metric,value:`${rate(d.current).toFixed(1)}%`,note:`${d.current[0]} / ${d.current[1]}，${d.periods[1]}`},{label:'较前期变化',value:`+${delta.toFixed(1)} 个百分点`,note:`前期 ${d.before[0]} / ${d.before[1]}`},{label:'同口径诊断样本',value:d.sampleCount,note:'一条样本只记录一个主因或待查原因'},{label:'待办改善事项',value:s.actions.filter(a=>a.status!=='已完成').length,note:'包括标准变更核对事项'}]}/><section className="panel"><PanelTitle title="业务结果与能力诊断" sub="先核对业务口径和样本，再区分知识、流程、系统、协同与人员能力原因。" icon={<ChartNoAxesCombined size={18}/> }><Picker label="业务诊断主题" value={selected} onChange={setSelected} options={s.diagnoses.map(x=>({value:x.id,label:x.name}))}/></PanelTitle><div className="mg-diagnosis-flow"><span>服务结果<b>{d.metric}</b></span><ArrowRight/><span>关联场景<b>{nameOf(s,d.scenarioId)}</b></span><ArrowRight/><span>具体任务<b>受理 / 记录 / 协同交接</b></span><ArrowRight/><span>验证依据<b>同口径样本与行为观察</b></span></div><DataTable headers={['原因分类','样本数 / 占比','诊断证据','判断状态','关联任务 / 能力','管理行动']} rows={d.causes.map(c=>[c.name,`${c.count} / ${(c.count/d.sampleCount*100).toFixed(1)}%`,<span className="mg-definition">{c.detail}</span>,<Badge tone={c.status==='待查'?'amber':'green'}>{c.status}</Badge>,<div><button className="text-button" onClick={()=>onDetail({type:'task',id:c.taskId})}>{nameOf(s,c.taskId)}</button><button className="text-button" onClick={()=>onDetail({type:'capability',id:c.capabilityId})}>{nameOf(s,c.capabilityId)}</button></div>,<button className="button outline" onClick={()=>{setCause(c.name);setTitle(c.status==='待查'?'补充行为样本并进行复核':`处理${c.name}`);setAcceptance('');setModal('newAction')}}>安排处置</button>])}/><Note>样本原因是合成演示的人工核查结论。业务异常与能力差距的关联不等于因果；待查样本不形成员工能力扣减。</Note></section>
 <section className="panel section-gap"><PanelTitle title="改善事项与结果跟踪" sub="每项行动有负责人、期限、验收材料和复核记录。"><Segments value={scope} onChange={setScope} options={[{value:'diagnosis',label:'当前业务诊断'},{value:'all',label:'全部改善事项'}]}/></PanelTitle><DataTable headers={['改善事项','责任人 / 截止日期','状态','验收要求','操作']} rows={actions.map(a=>[<div><b>{a.title}</b><small className="cell-note">{a.category}</small></div>,`${nameOf(s,a.ownerId)} / ${a.due}`,<Badge tone={a.status==='已完成'?'green':a.due<s.date?'amber':'blue'}>{a.due<s.date&&a.status!=='已完成'?'已逾期 · ':''}{a.status}</Badge>,<span className="mg-definition">{a.acceptance}</span>,a.status!=='已完成'?<button className="text-button" onClick={()=>{setActionId(a.id);setDeliverable(a.deliverable);setAcceptance('');setModal('action')}}>{a.status==='待办理'?'提交验收材料':'办理验收'}</button>:<span className="mg-definition">{a.deliverable}</span>])}/></section>
 <section className="panel section-gap"><PanelTitle title="同口径业务表现观察" sub="分子、分母、时间范围与场景保持透明；观察业务变化，不自动归因为培训效果。"/><div className="mg-trend">{[d.before,d.current,d.after].map((v,i)=><div key={i}><div className="mg-trend-track"><div style={{height:`${Math.min(100,rate(v)*5)}%`}}/><strong>{rate(v).toFixed(1)}%</strong></div><b>{['前期','异常期','后续观察期'][i]}</b><small>{d.periods[i]} · {v[0]} / {v[1]}</small></div>)}</div><Note>后续观察较异常期下降 {(rate(d.current)-rate(d.after)).toFixed(1)} 个百分点。仍需考虑诉求难度、业务量和同期知识、流程、系统调整；本图不证明由某项培养行动造成。</Note></section>
 <Modal open={modal==='newAction'} onClose={()=>setModal('')} title="安排诊断处置" sub={`${d.name} / ${cause}`}><Field label="行动名称" value={title} onChange={e=>setTitle(e.target.value)}/><div className="mg-form-grid"><label className="mg-field"><span>责任人</span><Picker label="改善事项责任人" value={owner} onChange={setOwner} options={base.people.map(p=>({value:p.id,label:p.name}))}/></label><Field label="完成期限" type="date" value={due} onChange={e=>setDue(e.target.value)}/></div><TextField label="验收条件与应提交材料" value={acceptance} onChange={setAcceptance}/><Actions><button className="button primary" onClick={()=>mutate(st=>{if(!title.trim()||!due||!acceptance.trim())throw new Error('请填写行动、期限和验收条件');st.actions.push({id:uid('ACT'),diagnosisId:d.id,category:cause,title,ownerId:owner,due,status:'待办理',deliverable:'',acceptance});addAudit(st,'创建改善事项',`${title} / ${nameOf(st,owner)}`);setModal('')})}>创建改善事项</button></Actions></Modal>
 <Modal open={modal==='action'} onClose={()=>setModal('')} title={action?.status==='待办理'?'提交验收材料':'改善事项验收'} sub={action?.title||''}><TextField label="已完成工作与证据材料" value={deliverable} onChange={setDeliverable}/>{action?.status==='待验收'&&<TextField label="验收结论与依据" value={acceptance} onChange={setAcceptance}/>}<Actions><button className="button primary" onClick={()=>mutate(st=>{const a=st.actions.find(a=>a.id===actionId)!;if(!deliverable.trim())throw new Error('请填写可核验的产出材料');if(a.status==='待办理'){a.deliverable=deliverable;a.status='待验收'}else if(a.status==='待验收'){if(!acceptance.trim())throw new Error('请填写验收依据');a.deliverable=`${deliverable}；验收：${acceptance}`;a.status='已完成'}else throw new Error('此事项已完成');addAudit(st,'改善事项流转',`${a.title} / ${a.status}`);setModal('')})}>{action?.status==='待办理'?'提交验收':'验收通过'}</button>{action?.status==='待验收'&&<button className="button outline" onClick={()=>mutate(st=>{if(!acceptance.trim())throw new Error('请填写退回依据');const a=st.actions.find(a=>a.id===actionId)!;a.status='待办理';a.deliverable=`${deliverable}；退回：${acceptance}`;addAudit(st,'退回改善事项',a.title);setModal('')})}>退回补充</button>}</Actions></Modal></>;
}
