'use client';
import {useState} from 'react';
import {ArrowUpRight,Grid2X2,Download} from 'lucide-react';
import {useManagement} from './management-context';
import {nameOf} from './management-model';
import {matrixCells,compareMatrix,scopePeople,type WorkContext} from './workflow-model';
import {exportCsv} from './model';
import {PanelTitle,Picker,DataTable,Badge,Note} from './ui-parts';
import {Modal,Field,Actions} from './management-ui';
export function OrganizationMatrix({roleId,onRole,onOpen}:{roleId:string;onRole:(id:string)=>void;onOpen:(page:string,context?:WorkContext)=>void}){
 const {state:s}=useManagement();const [org,setOrg]=useState('all'),[star,setStar]=useState('3'),[before,setBefore]=useState(s.versions[0].date),[cell,setCell]=useState<{orgId:string;capId:string}|null>(null);
 const ids=scopePeople(s,roleId,org);const columns=matrixCells(s,roleId,Number(star),org);const scopeIds=new Set([org]);let n=-1;while(n!==scopeIds.size){n=scopeIds.size;s.orgs.filter(o=>scopeIds.has(o.parentId)).forEach(o=>scopeIds.add(o.id))}
 const teams=s.orgs.filter(o=>o.type==='班组'&&(org==='all'||scopeIds.has(o.id))&&scopePeople(s,roleId,o.id).length);
 const rows=teams.map(o=>({org:o,cells:matrixCells(s,roleId,Number(star),o.id)}));
 const validBefore=before>=s.versions[0].date&&before<=s.date;const trend=validBefore?compareMatrix(s,roleId,Number(star),org,before):null;
 const selected=cell?matrixCells(s,roleId,Number(star),cell.orgId).find(c=>c.capabilityId===cell.capId):null;
 const output=()=>exportCsv('组织能力矩阵_模拟数据.csv',['组织','岗位','统一星级要求','能力','最低等级','已达标','未达标','待补证','适用人数','观察日期'],rows.flatMap(r=>r.cells.map(c=>[r.org.name,nameOf(s,roleId),star,nameOf(s,c.capabilityId),c.level??'未设置',c.achieved,c.gap,c.unknown,c.total,s.date])));
 return <><section className="panel"><PanelTitle title="组织能力矩阵" sub="逐项查看共性缺口与能力集中情况" icon={<Grid2X2 size={19}/> }><button className="button outline" onClick={output}><Download size={16}/>导出当前矩阵</button></PanelTitle><div className="mg-toolbar"><Actions><Picker label="矩阵组织范围" value={org} onChange={setOrg} options={[{value:'all',label:'全中心'},...s.orgs.map(o=>({value:o.id,label:o.name}))]}/><Picker label="矩阵岗位" value={roleId} onChange={onRole} options={s.catalog.nodes.filter(n=>n.kind==='role'&&n.active).map(n=>({value:n.id,label:n.name}))}/><Picker label="矩阵统一对标要求" value={star} onChange={setStar} options={[1,2,3,4,5].map(n=>({value:String(n),label:`统一对标 ${n} 星要求`}))}/></Actions><Badge>{ids.length} 名有效任职人员 · 按人去重</Badge></div><div className="v3-matrix-legend"><span><i className="green"/>已达标</span><span><i className="amber"/>未达标</span><span><i className="gray"/>待补证 / 待复核</span><span>点击格子查看对应人员</span></div><DataTable headers={['班组 / 岗位人数',...columns.map(c=>`${nameOf(s,c.capabilityId)} · L${c.level??'?'}`)]} rows={rows.map(r=>[<div><b>{r.org.name}</b><small className="cell-note">{scopePeople(s,roleId,r.org.id).length} 人</small></div>,...r.cells.map(c=><button className={`v3-matrix-cell ${c.unknown?'has-unknown':c.gap?'has-gap':'all-pass'}`} onClick={()=>setCell({orgId:r.org.id,capId:c.capabilityId})}><b>{c.achieved}<small> / {c.total} 人</small></b><span>未达标 {c.gap} · 待补证 {c.unknown}</span>{c.achieved===1&&c.total>1&&<em>达标能力集中于 1 人</em>}</button>)])}/><Note>矩阵按同一岗位、统一星级要求逐项核验；缺证单列。这里的能力达标人数，还需结合场景授权和排班才构成当班独立供给。</Note></section>
 <section className="panel section-gap"><PanelTitle title="同口径变化对照" sub="固定同一批任职人员，分别观察达标、差距和证据状态"/><div className="mg-toolbar"><Field label="对照日期" type="date" min={s.versions[0].date} max={s.date} value={before} onChange={e=>setBefore(e.target.value)}/><span>当前观察日期：{s.date}</span></div>{!trend?<Note>请选择标准快照范围内、且不晚于当前观察日期的时间。</Note>:<><div className="mg-inset"><Badge tone={trend.comparable?'green':'amber'}>{trend.comparable?'岗位要求与行为标准可比':'标准变化，暂不可直接比较'}</Badge><p>固定队列 {trend.cohort.length} 人；调入 {trend.entered.length} 人，调出 {trend.left.length} 人。人员变化不计入固定队列。</p><small>{trend.beforeVersion} → {trend.afterVersion}</small></div>{trend.comparable&&trend.cohort.length>0?<DataTable headers={['能力 / 统一要求',`${before} · 达标 / 未达标 / 待补证`,`${s.date} · 达标 / 未达标 / 待补证`,'已确认达标人数变化']} rows={trend.after.map(c=>{const b=trend.before.find(x=>x.capabilityId===c.capabilityId)!;const delta=c.achieved-b.achieved;return [nameOf(s,c.capabilityId)+` · L${c.level}`,`${b.achieved} / ${b.gap} / ${b.unknown}`,`${c.achieved} / ${c.gap} / ${c.unknown}`,<Badge tone={delta>0?'green':delta<0?'amber':'gray'}>{delta>0?'+':''}{delta} 人</Badge>]})}/>:<Note>{trend.comparable?'暂无同时在两个日期任职的可比人员。':'目标等级、必选要求或行为定义发生变化，暂停差值计算；可切换至新标准生效后的日期比较。'}</Note>}<Note>证据补充或到期也会改变已确认达标人数，因此人数变化不直接解释为能力提升或下降。历史投影仅使用该时点已生效的评价记录。</Note></>}</section>
 <Modal open={!!cell} onClose={()=>setCell(null)} title={cell?`${nameOf(s,cell.orgId)} · ${nameOf(s,cell.capId)}`:''} sub={`统一对标 ${star} 星要求 · L${selected?.level??'—'} · ${s.date}`}><DataTable headers={['人员','当前结论','下一步']} rows={(selected?.rows||[]).map(p=>[nameOf(s,p.id),<Badge tone={p.status==='achieved'?'green':p.status==='gap'?'amber':'gray'}>{{achieved:'已达标',gap:'未达标',unknown:'待补证 / 待复核'}[p.status]}</Badge>,<button className="text-button" onClick={()=>{setCell(null);onOpen(p.status==='unknown'?'evaluation':'talent',{personId:p.id,roleId,capabilityId:cell?.capId,tab:p.status==='unknown'?'new':undefined})}}>查看与办理<ArrowUpRight size={14}/></button>])}/></Modal></>;
}
