'use client';
import {useState} from 'react';
import {BookOpen,ArrowUpRight,Library,Layers3} from 'lucide-react';
import {foundation,profileFor} from './foundation';
import {capById,roles} from './model';
import {Badge,DataTable,Note,PanelTitle,Picker,SearchBox} from './ui-parts';
import {useManagement} from './management-context';
import type {DetailRef} from './graph-view';

export function StarReference(){return <div className="foundation-scale"><div className="foundation-scale-heading"><b>统一能力对标要求</b><Badge tone="gray">图片示意 · 非职级换算</Badge></div><div className="foundation-stars">{foundation.starDefinitions.map(x=><div key={x.star}><span>{'★'.repeat(x.star)}</span><b>{x.name}</b></div>)}</div><p>一星从基础业务独立处理起步。业务能力与 AI 协作分别核验；综合星级仍须完整评审。岗位职级按修订稿另行登记，班长、支撑及运营岗位不以此处五星标尺替代一至三级职级。</p></div>}

export function ReferenceStandards(){return <details className="panel reference-details"><summary>附件依据与口径说明 <span>3 份来源 · {foundation.conflicts.length} 项待确认</span></summary><Note>目录及制度条款摘自修订稿，能力族与统一对标定义来自用户图片；行为细化、人员、知识内容及业务数据是合成示例。此页不作正式晋升结论。</Note><DataTable headers={['资料','采用内容与定位','资料性质']} rows={foundation.sources.map(s=>[s.name,<span className="wrap-cell">{s.locator}</span>,<Badge tone="blue">{s.nature}</Badge>])}/><h3 className="detail-section-heading">职级规则参考</h3><DataTable headers={['规则','附件内容','来源定位']} rows={foundation.rules.map(r=>[r.title,<span className="wrap-cell">{r.text}</span>,r.locator])}/><h3 className="detail-section-heading">原文冲突与待确认项</h3><DataTable headers={['事项','待确认原因','原文位置','状态']} rows={foundation.conflicts.map(r=>[r.title,<span className="wrap-cell">{r.detail}</span>,r.locator,<Badge tone="amber">{r.status}</Badge>])}/><Note>以上修订稿规则尚未启用为原型自动评分或晋升规则；培训积分不擅自增加权重，比例表不以模拟人员总数代替岗位定员。</Note></details>}

export function ReferenceJobs({onDetail}:{onDetail:(d:DetailRef)=>void}){
 const [sequence,setSequence]=useState('all'),[query,setQuery]=useState('');
 const shown=foundation.jobs.filter(j=>(sequence==='all'||sequence===j.sequenceId)&&j.name.includes(query.trim()));
 return <section className="panel reference-jobs"><PanelTitle title="岗位名称参考目录" sub="三个序列、30 个岗位名称，依据修订稿正文整理；当前能力墙展示其中六个履职样本。" icon={<Library size={18}/>}/><div className="table-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="搜索岗位名称"/><Picker label="岗位目录序列" value={sequence} onChange={setSequence} options={[{value:'all',label:'全部序列'},...foundation.sequences.map(s=>({value:s.id,label:s.name}))]}/></div><DataTable headers={['岗位名称','序列','职级制度','当前履职样本']} rows={shown.map(j=>[j.name,foundation.sequences.find(s=>s.id===j.sequenceId)?.name,j.rankScheme,<div className="tag-list">{foundation.profiles.some(p=>p.jobId===j.id)?foundation.profiles.filter(p=>p.jobId===j.id).map(p=><button className="text-button" key={p.roleId} onClick={()=>onDetail({type:'role',id:p.roleId})}>{roles.find(r=>r.id===p.roleId)?.name}<ArrowUpRight size={13}/></button>):<Badge tone="gray">目录已收录 · 标准待建模</Badge>}</div>])}/><div className="table-summary">{shown.length} / {foundation.jobs.length} 个岗位名称 · 来源：岗位职级办法修订稿第2—4页</div><div className="foundation-schemes">{foundation.rankSchemes.map(s=><div key={s.name}><b>{s.name}</b><p>{s.levels.join(' → ')}</p><small>{s.locator}</small></div>)}</div><Note>“综合业务、报修查询、投诉举报”是业务样本范围。二星及以上服务专员应具备全业务技能，单一场景达标不能证明完整岗位资格。编制、人员登记职级与能力要求分别维护。</Note></section>
}

export function KnowledgeReference({onDetail}:{onDetail:(d:DetailRef)=>void}){
 const {state:s}=useManagement();const [type,setType]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState(foundation.knowledge[0].id);
 const list=foundation.knowledge.filter(k=>(type==='all'||type===k.type)&&`${k.title}${k.id}`.includes(query.trim()));const k=list.find(k=>k.id===selected)||list[0];
 return <div className="knowledge-reference"><PanelTitle title="知识内容与版本样本" sub="六类知识、12 条合成记录；用于演示任务引用、知识核验和版本追溯。" icon={<BookOpen size={18}/>}/><div className="table-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="搜索知识名称或编码"/><Picker label="知识类型" value={type} onChange={setType} options={[{value:'all',label:'全部知识类型'},...foundation.knowledgeTypes.map(t=>({value:t,label:t}))]}/></div><DataTable headers={['知识记录','类型','发布版本 / 有效期','质量 / 渠道同步','查看']} rows={list.map(k=>[k.title,k.type,<div>{k.version} · {k.publicationStatus}<small className="cell-note">{k.effectiveFrom} 至 {k.effectiveUntil}</small></div>,<div><Badge>内容质量{k.qualityStatus}</Badge> <Badge tone={k.channels.some(c=>c.syncStatus!=='已同步')?'amber':'green'}>{k.channels.some(c=>c.syncStatus!=='已同步')?'存在渠道版本差异':'渠道已同步'}</Badge></div>,<button className="text-button" onClick={()=>setSelected(k.id)}>查看引用<ArrowUpRight size={13}/></button>])}/>{k&&<div className="knowledge-detail"><div className="tag-list"><Badge>{k.type}</Badge><Badge tone="blue">{k.id} · {k.version}</Badge><Badge tone="gray">合成内容</Badge></div><h3>{k.title}</h3><p>{k.content}</p><div className="record-meta"><span>来源记录 <b>{k.sourceDocument}</b></span><span>原文定位 <b>{k.sourceLocator}</b></span><span>责任专业 <b>{k.owner}</b></span><span>适用范围 <b>{k.region}</b></span><span>观察日期有效性 <b>{s.date<k.effectiveFrom?'尚未生效':s.date>k.effectiveUntil?'已过期':'有效期内'}</b></span><span>上一版本 <b>{k.previousVersion||'首版示例'}</b></span></div><DataTable headers={['服务渠道','渠道版本','最近同步','与发布版本对照']} rows={k.channels.map(c=>[c.channel,c.version,c.syncedAt,<Badge tone={c.version===k.version?'green':'amber'}>{c.syncStatus}</Badge>])}/><DataTable headers={['历史版本','有效期间','状态']} rows={k.versions.map(v=>[v.version,`${v.effectiveFrom} 至 ${v.effectiveUntil}`,v.status])}/><h4>关联任务与行为要求</h4><div className="related-role-cards">{k.taskIds.map(id=><button key={id} onClick={()=>onDetail({type:'task',id})}>{id} · 查看任务<ArrowUpRight size={13}/></button>)}</div><div className="tag-list section-gap">{k.capabilityIds.map(id=><button key={id} onClick={()=>onDetail({type:'capability',id})}><Badge tone="gray">{capById(id)?.name||id}</Badge></button>)}</div>{foundation.knowledgeFeedback.filter(f=>f.knowledgeId===k.id).map(f=><Note key={f.id}>{f.description} · 办理状态：{s.actions.find(a=>a.id===f.actionId)?.status||f.status}（关联现有整改待办）。</Note>)}</div>}<Note>知识分类及追溯字段参考技术方案的知识类型、加工和来源定位章节。示例知识内容、发布状态及渠道状态为原型设计；检索和引用事实不直接证明能力达标。</Note></div>
}

export function KnowledgeLinks({taskId,evidenceId,onDetail}:{taskId?:string;evidenceId?:string;onDetail?:(d:DetailRef)=>void}){
 const refs=evidenceId?foundation.evidenceKnowledge.filter(e=>e.evidenceId===evidenceId):[];const items=foundation.knowledge.filter(k=>taskId?k.taskIds.includes(taskId):refs.some(e=>e.knowledgeId===k.id));
 if(!items.length)return null;
 return <div className="reference-links"><h3 className="detail-section-heading">{evidenceId?'当时引用的知识版本（模拟）':'可使用的知识依据（模拟）'}</h3>{items.map(k=>{const r=refs.find(r=>r.knowledgeId===k.id);return <div key={k.id} className="resource-reference"><BookOpen size={18}/><div><b>{k.title}</b><p>{k.type} · {r?.usedVersion||k.version} · {r?.sourceLocator||k.sourceLocator}</p>{r&&<small>使用时点：{r.usedAt} · {r.channel} · 行为观察另行复核</small>}<small>{k.sourceDocument} · 来源内容为合成记录</small>{r&&<small>{r.note}</small>}</div></div>})}</div>
}

export function DevelopmentReference(){return <details className="panel reference-details"><summary>岗位发展通道参考 <span>修订稿条件 · 不自动晋升</span></summary><DataTable headers={['当前岗位条件','发展方向','申报条件摘录','来源']} rows={foundation.developmentPaths.map(p=>[p.from,p.to,<span className="wrap-cell">{p.condition}</span>,p.locator])}/><Note>实际发展还需完整资格核验、实践经历、考试及人资评审。首席、六星和客服经理等冲突条款列在“岗位与业务标准”的附件说明中，未写成自动准入规则。</Note></details>}
