'use client';
import {DevelopmentReference} from './reference-panels';
import {useEffect,useRef,useState} from 'react';
import {TalentFocus} from './talent-focus-view';
import {TalentPlanDialog} from './talent-plan-dialog';
import {GraduationCap,Plus,ArrowRight,CheckCheck} from 'lucide-react';
import {useManagement} from './management-context';
import {base,nameOf,qualification,addAudit,personAt,currentVersion,type Development} from './management-model';
import {requestDevelopmentReview,developmentStatus,confirmDevelopment,type WorkContext,type ViewRole} from './workflow-model';
import {Picker,Badge,DataTable,PanelTitle,Note,Segments} from './ui-parts';
import {TextField,Modal,KPI,Actions} from './management-ui';

export function TalentView({onNavigate,onPerson,context={},onOpen,viewRole='体系管理员',viewerId='DEMO-016'}:{onNavigate:(p:string)=>void;onPerson:(id:string)=>void;context?:WorkContext;onOpen?:(page:string,context?:WorkContext)=>void;viewRole?:ViewRole;viewerId?:string}){
 const {state:s,mutate}=useManagement();const [view,setView]=useState(context.personId||viewRole==='员工'?'person':'all');const [filterPerson,setFilterPerson]=useState(context.personId||viewerId);const [selected,setSelected]=useState(context.recordId||'');const [modal,setModal]=useState('');const [editId,setEditId]=useState('');const [personId]=useState(context.personId||viewerId);const [milestone,setMilestone]=useState(0);const [evidence,setEvidence]=useState('');const [resource,setResource]=useState('');
 const focusRef=useRef<HTMLElement|null>(null);const handledFocus=useRef(0);const [focusRequest,setFocusRequest]=useState(context.recordId?1:0);
 const rows=s.development.filter(d=>view==='person'?d.personId===filterPerson:view==='mentor'?d.mentorId===filterPerson:view==='reserve'?d.purpose==='后备培养':true);const d=rows.find(x=>x.id===selected)||rows[0];const policy=d?s.policies.find(p=>p.id===d.targetPolicyId):null;const q=d&&policy?qualification(s,d.personId,policy.id):null;const status=d?developmentStatus(s,d):'';
 useEffect(()=>{if(!focusRequest||focusRequest===handledFocus.current||!d)return;const frame=requestAnimationFrame(()=>{handledFocus.current=focusRequest;focusRef.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'start'});focusRef.current?.focus({preventScroll:true})});return()=>cancelAnimationFrame(frame)},[focusRequest,d?.id]);
 const open=(page:string,ctx:WorkContext)=>{onPerson(ctx.personId||personId);if(onOpen)onOpen(page,ctx);else onNavigate(page)};
 const start=(old?:Development)=>{setEditId(old?.id||'');setModal('new')};
 const newPlanPerson=view==='person'?filterPerson:view==='mentor'?'':context.personId||'';
 const usePlanContext=view!=='mentor'&&(!newPlanPerson||newPlanPerson===context.personId);
 const resources=policy?base.growthResources.filter(r=>r.capabilityIds.some(id=>policy.requirements.some(c=>c.capabilityId===id))):[];
 return <><KPI items={[{label:'统一培养计划',value:s.development.length,note:'个人、导师与梯队视图共用记录'},{label:'目标待确认',value:s.development.filter(d=>!d.targetConfirmed).length,note:'历史进度保留，缺少的目标须补齐'},{label:'等待评价办理',value:s.development.filter(d=>['复测待取证','评价待复核','评价退回，需补充'].includes(developmentStatus(s,d))).length,note:'对应实际的模拟评价任务'},{label:'培养目标已确认',value:s.development.filter(d=>developmentStatus(s,d)==='培养目标已确认').length,note:'任职、星级与上岗授权分别办理'}]}/>
 <section className="panel"><PanelTitle title="人才梯队与岗位发展路径" sub="一份培养计划贯通目标、课程、实践、导师和评价记录" icon={<GraduationCap size={18}/> }><button className="button primary" onClick={()=>start()}><Plus size={15}/>建立培养计划</button></PanelTitle><div className="mg-toolbar"><Segments value={view} onChange={setView} options={[{value:'all',label:'全部计划'},{value:'person',label:'个人成长'},{value:'mentor',label:'导师带教'},{value:'reserve',label:'后备梯队'}]}/>{['person','mentor'].includes(view)&&<Picker label={view==='mentor'?'带教导师':'培养人员筛选'} value={filterPerson} onChange={v=>{setFilterPerson(v);setSelected('')}} options={base.people.map(p=>({value:p.id,label:p.name}))}/>}</div><DataTable headers={['培养人员','目标岗位 / 场景','计划类型 / 通道','导师 / 周期','当前阶段','操作']} rows={rows.map(x=>[nameOf(s,x.personId),<div>{x.targetConfirmed?nameOf(s,x.targetRoleId):'历史目标待确认'}<small className="cell-note">{s.policies.find(p=>p.id===x.targetPolicyId)?.name||'保留旧训练记录，待完善目标'}</small></div>,`${x.purpose} / ${x.track}`,`${x.mentorId?nameOf(s,x.mentorId):'待明确导师'} / ${x.months} 个月`,<Badge tone={developmentStatus(s,x)==='培养目标已确认'?'green':'blue'}>{developmentStatus(s,x)}</Badge>,<button className="text-button" onClick={()=>{setSelected(x.id);onPerson(x.personId);setFocusRequest(value=>value+1)}}>查看并办理</button>])}/></section>
 {d&&<section className="panel section-gap talent-plan-detail" ref={focusRef} tabIndex={-1} aria-label={nameOf(s,d.personId)+"的培养重点"}><TalentFocus state={s} plan={d} onConfigure={()=>start(d)}/><details className="talent-plan-management"><summary><span>办理与计划记录</span><small>课程、实践、导师确认及评价</small></summary><PanelTitle title={`${nameOf(s,d.personId)} · 培养计划`} sub={`${d.id} · 计划建立于 ${d.created} · ${d.due?`完成期限 ${d.due}`:'尚未分派完成期限'}`}><Badge tone={status==='培养目标已确认'?'green':'amber'}>{status}</Badge></PanelTitle><div className="mg-inset">{!d.targetConfirmed?<div className="mg-risk-callout"><b>历史训练进度已保留，目标信息需补齐</b><p>旧记录没有保存当时选择的目标岗位、场景和导师。完善后才能衔接评价。</p><button className="button primary" onClick={()=>start(d)}>完善并确认目标</button></div>:<div className="v3-plan-goal"><div><span>目标岗位与场景</span><b>{nameOf(s,d.targetRoleId)} · {policy?.name||'原目标已停用'}</b><p>{d.wish}</p></div><div><span>导师与发展通道</span><b>{nameOf(s,d.mentorId)} · {d.track}</b><p>{d.targetVersion} → 当前 {currentVersion(s)}</p></div></div>}
 {q&&<DataTable headers={['目标能力','当前记录','目标要求','差距与证据']} rows={q.checks.map(c=>[nameOf(s,c.capabilityId),c.levelNow===null?'未知':`L${c.levelNow}`,`L${c.level}`,<Badge tone={c.passed?'green':c.known?'amber':'gray'}>{c.reason}</Badge>])}/>}<h3 className="mg-section-label">课程与训练任务</h3><DataTable headers={['训练资源','过程记录','下一步']} rows={(d.resources||[]).map(r=>[base.growthResources.find(x=>x.id===r.resourceId)?.name||`历史资源 ${r.resourceId}`,<div><Badge tone={r.trained?'green':'gray'}>{r.trained?'训练已完成':'待训练'}</Badge><small className="cell-note">{r.note}</small></div>,r.trained?<span>进入实践与复测</span>:<button className="button outline" onClick={()=>{setResource(r.resourceId);setEvidence('');setModal('train')}}>记录训练产出</button>])}/>{d.targetConfirmed&&status!=='培养目标已确认'&&<Actions><Picker label="添加匹配训练资源" value={resource} onChange={setResource} options={[{value:'',label:'选择与目标能力匹配的资源'},...resources.map(r=>({value:r.id,label:r.name}))]}/><button className="button outline" onClick={()=>mutate(st=>{const dev=st.development.find(x=>x.id===d.id)!;if(!resource||!resources.some(r=>r.id===resource))throw new Error('请选择目标能力对应的训练资源');if(dev.resources?.some(r=>r.resourceId===resource))throw new Error('此资源已在本计划中');dev.resources??=[];dev.resources.push({resourceId:resource,trained:false,note:''});addAudit(st,'安排培养训练',`${dev.id} / ${resource}`)})}>加入本计划</button></Actions>}
 <h3 className="mg-section-label">必需实践与导师确认</h3><div className="mg-milestones">{d.milestones.map((m,i)=><div key={i} className={m.done?'done':''}><span className="mg-step-number">{m.done?<CheckCheck size={18}/>:i+1}</span><div><b>{m.name}</b><p>{m.evidence||'待提交实践产出和导师观察记录'}</p></div><button className="button outline" disabled={m.done||m.systemReview||!d.targetConfirmed} onClick={()=>{setMilestone(i);setEvidence('');setModal('milestone')}}>{m.systemReview?(q?.status==='达标'?'目标条件已满足':'由评价结果核验'):m.done?'已确认':'记录实践'}</button></div>)}</div>
 {(d.confirmations||[]).length>0&&<><h3 className="mg-section-label">培养确认历史</h3><DataTable headers={['确认日期','确认人','依据']} rows={d.confirmations!.map(c=>[c.date,c.reviewer,c.reason])}/></>}<h3 className="mg-section-label">关联评价与结果回流</h3><DataTable headers={['能力 / 场景','评价阶段','结果','办理']} rows={s.assessments.filter(a=>(d.assessmentIds||[]).includes(a.id)).map(a=>[`${nameOf(s,a.capabilityId)} / ${nameOf(s,a.scenarioId)}`,a.status,a.resultLevel===null?'待核验':`L${a.resultLevel}`,<button className="text-button" onClick={()=>open('evaluation',{personId:d.personId,recordId:a.id,scenarioId:a.scenarioId,capabilityId:a.capabilityId})}>继续办理评价</button>])}/><Actions><button disabled={!d.targetConfirmed||status==='培养目标已确认'} className="button primary" onClick={()=>{let ids:string[]=[];if(mutate(st=>{ids=requestDevelopmentReview(st,d.id)})){if(ids[0])open('evaluation',{personId:d.personId,recordId:ids[0],policyId:d.targetPolicyId,scenarioId:policy?.scenarioId})}}}>建立或继续目标能力复测<ArrowRight size={15}/></button><button disabled={status!=='条件满足，待确认'} className="button outline" onClick={()=>mutate(st=>confirmDevelopment(st,d.id))}>模拟确认培养目标</button>{d.targetConfirmed&&<button className="text-button" onClick={()=>open('authorization',{personId:d.personId,policyId:d.targetPolicyId})}>查看场景授权条件</button>}</Actions></div><Note>训练与实践只记录过程。独立取证、评价复核后形成能力结果，满足目标条件才可确认培养完成；不会自动升星、调岗或增加当班独立供给。</Note></details></section>}
 <DevelopmentReference/>
 {modal==='new'&&<TalentPlanDialog editing={s.development.find(plan=>plan.id===editId)} initialPersonId={newPlanPerson} initialRoleId={usePlanContext?context.roleId:undefined} initialPolicyId={usePlanContext?context.policyId:undefined} onClose={()=>setModal('')} onSaved={(id,pid)=>{setSelected(id);setView('person');setFilterPerson(pid);onPerson(pid);setModal('');setFocusRequest(value=>value+1)}} onExisting={(id,pid)=>{setSelected(id);setView('person');setFilterPerson(pid);onPerson(pid);setModal('');setFocusRequest(value=>value+1)}}/>}
 <Modal open={modal==='train'||modal==='milestone'} onClose={()=>setModal('')} title={modal==='train'?'记录训练产出':'记录实践与导师确认'} sub={modal==='train'?(base.growthResources.find(r=>r.id===resource)?.name||resource):d?.milestones[milestone]?.name||''}><TextField label="产出与可核验依据" value={evidence} onChange={setEvidence}/><Actions><button className="button primary" onClick={()=>{if(mutate(st=>{if(!d||!evidence.trim())throw new Error('请填写可核验的产出与依据');const dev=st.development.find(x=>x.id===d.id)!;if(modal==='train'){const r=dev.resources!.find(r=>r.resourceId===resource)!;if(r.trained)throw new Error('训练已经完成');r.trained=true;r.note=evidence}else{if(!dev.mentorId||dev.milestones[milestone].done)throw new Error('导师未明确或实践已经确认');dev.milestones[milestone]={...dev.milestones[milestone],done:true,evidence:`${evidence}；导师 ${nameOf(st,dev.mentorId)}，${st.date} 模拟确认`}}addAudit(st,modal==='train'?'记录训练产出':'导师确认实践',`${dev.id} / ${evidence}`)}))setModal('')}}>保存过程记录</button></Actions></Modal></>;
}
