'use client';
import {useState} from 'react';
import {GraduationCap,Plus,ArrowRight,Users,CheckCheck,Target} from 'lucide-react';
import {useManagement} from './management-context';
import {base,nameOf,qualification,uid,addAudit,personAt,currentVersion,type Development} from './management-model';
import {Picker,Badge,DataTable,PanelTitle,Note,Segments} from './ui-parts';
import {Field,TextField,Modal,KPI,Actions} from './management-ui';

export function TalentView({onNavigate,onPerson}:{onNavigate:(p:string)=>void;onPerson:(id:string)=>void}){
 const {state:s,mutate}=useManagement();const [track,setTrack]=useState('all');const [selected,setSelected]=useState('DEV-01');const [modal,setModal]=useState('');const [personId,setPersonId]=useState('DEMO-016');const [targetRole,setTargetRole]=useState('ROLE-02');const [targetPolicy,setTargetPolicy]=useState('POL-EXPERT');const [newTrack,setNewTrack]=useState('专业发展');const [mentor,setMentor]=useState('DEMO-020');const [months,setMonths]=useState('3');const [wish,setWish]=useState('');const [milestone,setMilestone]=useState(0);const [evidence,setEvidence]=useState('');
 const d=s.development.find(x=>x.id===selected)||s.development[0];const q=d?qualification(s,d.personId,d.targetPolicyId):null;
 const rows=s.development.filter(d=>track==='all'||d.track===track);const roleNodes=s.catalog.nodes.filter(n=>n.kind==='role'&&n.active);
 return <><KPI items={[{label:'培养中的后备',value:s.development.filter(d=>d.status==='培养中').length,note:'后备不计入当前独立供给'},{label:'具备候选条件',value:s.development.filter(d=>d.status==='后备就绪'&&qualification(s,d.personId,d.targetPolicyId).status==='达标').length,note:'任职与场景授权仍需单独办理'},{label:'参与导师',value:new Set(s.development.map(d=>d.mentorId)).size,note:'查看每名导师的带教任务数量'},{label:'发展通道',value:'专业 / 管理',note:'按意愿、实践经历与目标条件安排'}]}/><section className="panel"><PanelTitle title="人才梯队与岗位发展路径" sub="从目标岗位出发，明确能力条件、实践经历、导师和培养周期。" icon={<GraduationCap size={18}/> }><button className="button primary" onClick={()=>setModal('new')}><Plus size={15}/>建立后备培养计划</button></PanelTitle><div className="mg-career-paths"><div><span>专业发展</span><b>常规独立办理<ArrowRight/>复杂情景处置<ArrowRight/>专业骨干<ArrowRight/>专家与导师</b><p>以场景复杂度、独立处置和指导改进能力为依据</p></div><div><span>管理发展</span><b>业务骨干<ArrowRight/>班组带教<ArrowRight/>班组管理<ArrowRight/>运营统筹</b><p>补充现场辅导、队伍配置、质量改进和跨专业协同经历</p></div></div><div className="mg-toolbar"><Segments value={track} onChange={setTrack} options={[{value:'all',label:'全部梯队'},{value:'专业发展',label:'专业通道'},{value:'管理发展',label:'管理通道'}]}/></div><DataTable headers={['培养人员','目标岗位 / 场景','发展意愿','导师 / 周期','实践与状态','操作']} rows={rows.map(x=>[nameOf(s,x.personId),<div>{nameOf(s,x.targetRoleId)}<small className="cell-note">{s.policies.find(p=>p.id===x.targetPolicyId)?.name}</small></div>,<span className="mg-definition">{x.wish}</span>,`${nameOf(s,x.mentorId)} / ${x.months} 个月`,<div>{x.milestones.filter(m=>m.done).length}/{x.milestones.length} 项实践<small className="cell-note">{x.status==='后备就绪'&&qualification(s,x.personId,x.targetPolicyId).status!=='达标'?'标准或证据变化，待重新确认':x.status}</small></div>,<button className="text-button" onClick={()=>setSelected(x.id)}>查看培养路径</button>])}/></section>
 {d&&q&&<section className="panel section-gap"><PanelTitle title={`${nameOf(s,d.personId)}的后备培养路径`} sub={`${d.track} · ${d.months} 个月 · 导师 ${nameOf(s,d.mentorId)} · ${currentVersion(s)}`}><Badge tone={q.status==='达标'?'green':'amber'}>{q.status}</Badge></PanelTitle><div className="mg-inset"><div className="mg-risk-callout"><b>目标：{s.policies.find(p=>p.id===d.targetPolicyId)?.name}</b><p>发展意愿：{d.wish}</p><p>导师现有带教计划：{s.development.filter(x=>x.mentorId===d.mentorId&&x.status!=='后备就绪').length} 项。是否安排当班带教需另行核实可用时间。</p></div><DataTable headers={['目标能力','当前记录','目标要求','差距 / 证据']} rows={q.checks.map(c=>[nameOf(s,c.capabilityId),c.levelNow===null?'未知':`L${c.levelNow}`,`L${c.level}`,<Badge tone={c.passed?'green':c.known?'amber':'gray'}>{c.reason}</Badge>])}/><h3 className="mg-section-label">必需实践经历与导师确认</h3><div className="mg-milestones">{d.milestones.map((m,i)=><div key={i} className={m.done?'done':''}><span className="mg-step-number">{m.done?<CheckCheck size={18}/>:i+1}</span><div><b>{m.name}</b><p>{m.evidence||'等待提交实践产出与导师观察记录'}</p></div><button className="button outline" disabled={m.done} onClick={()=>{setMilestone(i);setEvidence('');setModal('milestone')}}>{m.done?'已确认':'记录实践与导师确认'}</button></div>)}</div><Actions><button className="button primary" onClick={()=>mutate(st=>{const dev=st.development.find(x=>x.id===d.id)!;const checks=qualification(st,dev.personId,dev.targetPolicyId).checks.filter(c=>!c.passed);checks.forEach(c=>{if(st.assessments.some(a=>a.personId===dev.personId&&a.capabilityId===c.capabilityId&&a.scenarioId===st.policies.find(p=>p.id===dev.targetPolicyId)!.scenarioId&&['草稿','待复核'].includes(a.status)))return;st.assessments.push({id:uid('ASSESS'),personId:dev.personId,capabilityId:c.capabilityId,scenarioId:st.policies.find(p=>p.id===dev.targetPolicyId)!.scenarioId,targetLevel:c.level,status:'草稿',submitter:'班组评价员（模拟）',reviewer:'',reason:'',factIds:[],version:currentVersion(st),previousLevel:c.levelNow,resultLevel:null,created:st.date,effective:''})});dev.status='待复核';addAudit(st,'提交后备复测',`${nameOf(st,dev.personId)} / ${checks.length} 项待核验`);onPerson(dev.personId);onNavigate('evaluation')})}>建立目标能力复测并办理</button><button className="button outline" disabled={d.status==='后备就绪'} onClick={()=>mutate(st=>{const dev=st.development.find(x=>x.id===d.id)!;if(dev.milestones.some(m=>!m.done))throw new Error('必需实践经历尚未全部确认');if(qualification(st,dev.personId,dev.targetPolicyId).status!=='达标')throw new Error('目标能力和有效证据尚未全部满足，请先完成复测复核');dev.status='后备就绪';addAudit(st,'确认后备候选条件',`${nameOf(st,dev.personId)} / 由人才发展负责人模拟确认`)})}>模拟确认后备候选条件</button></Actions><Note>实践完成只记录培养过程。目标能力经独立评价复核后，才能确认后备候选条件；该状态不自动增加当班供给，也不自动调岗或升星。</Note></div></section>}
 <Modal open={modal==='new'} onClose={()=>setModal('')} title="建立后备培养计划" sub="培养计划须有明确目标、本人意愿、导师和实践路径。"><div className="mg-form-grid"><label className="mg-field"><span>培养人员</span><Picker label="培养人员" value={personId} onChange={setPersonId} options={base.people.map(p=>({value:p.id,label:p.name}))}/></label><label className="mg-field"><span>发展通道</span><Picker label="人才发展通道" value={newTrack} onChange={setNewTrack} options={['专业发展','管理发展'].map(v=>({value:v,label:v}))}/></label><label className="mg-field"><span>目标岗位</span><Picker label="人才目标岗位" value={targetRole} onChange={v=>{setTargetRole(v);setTargetPolicy(s.policies.find(p=>p.roleId===v)?.id||'')}} options={roleNodes.map(r=>({value:r.id,label:r.name}))}/></label><label className="mg-field"><span>目标场景条件</span><Picker label="人才目标场景" value={targetPolicy} onChange={setTargetPolicy} options={s.policies.filter(p=>p.roleId===targetRole).map(p=>({value:p.id,label:p.name}))}/></label><label className="mg-field"><span>导师</span><Picker label="人才培养导师" value={mentor} onChange={setMentor} options={base.people.filter(p=>p.id!==personId).map(p=>({value:p.id,label:p.name}))}/></label><Field label="培养周期（月）" type="number" min="1" max="24" step="1" value={months} onChange={e=>setMonths(e.target.value)}/></div><TextField label="本人发展意愿与沟通记录" value={wish} onChange={setWish}/><Actions><button className="button primary" onClick={()=>mutate(st=>{if(!wish.trim()||!Number.isInteger(Number(months))||Number(months)<1||Number(months)>24||mentor===personId||!targetPolicy)throw new Error('请填写发展意愿、有效导师、目标场景及1—24个月周期');if(st.development.some(d=>d.personId===personId&&d.targetPolicyId===targetPolicy&&d.status!=='后备就绪'))throw new Error('此人员已有相同目标培养计划');if(qualification(st,mentor,targetPolicy).status!=='达标')throw new Error('导师尚未满足目标场景能力与证据要求');const id=uid('DEV');st.development.push({id,personId,targetRoleId:targetRole,targetPolicyId:targetPolicy,track:newTrack as Development['track'],mentorId:mentor,months:Number(months),wish,status:'培养中',created:st.date,milestones:(newTrack==='管理发展'?['完成班组运营跟岗与排班案例分析','独立组织质量复盘与现场辅导并由导师确认','完成目标场景实操评价和复核']:['完成目标业务复杂案例跟班','独立提交目标场景案例复盘并由导师确认','完成目标场景实操评价和复核']).map(name=>({name,done:false,evidence:''}))});addAudit(st,'建立后备培养计划',`${nameOf(st,personId)} → ${nameOf(st,targetRole)}`);setSelected(id);setModal('')})}>保存培养计划</button></Actions></Modal>
 <Modal open={modal==='milestone'} onClose={()=>setModal('')} title="记录实践与导师确认" sub={d?.milestones[milestone]?.name||''}><TextField label="实践产出、观察记录与导师确认依据" value={evidence} onChange={setEvidence}/><Actions><button className="button primary" onClick={()=>mutate(st=>{if(!evidence.trim())throw new Error('请记录可核验的实践产出与导师依据');const dev=st.development.find(x=>x.id===d.id)!;if(dev.milestones[milestone].done)throw new Error('该实践已经确认');dev.milestones[milestone]={...dev.milestones[milestone],done:true,evidence:`${evidence}；导师 ${nameOf(st,dev.mentorId)}（模拟确认）`};addAudit(st,'确认培养实践',`${nameOf(st,dev.personId)} / ${dev.milestones[milestone].name}`);setModal('')})}>记录导师模拟确认</button></Actions></Modal></>;
}
