'use client';
import {useState} from 'react';
import {ListChecks,ArrowUpRight,Users,CalendarClock} from 'lucide-react';
import {useManagement} from './management-context';
import {base,nameOf,personAt,supply,addAudit,type State} from './management-model';
import {visibleTodos,todos,developmentStatus,dayAfter,type ViewRole,type WorkContext,type Todo} from './workflow-model';
import {Picker,Segments,PanelTitle,DataTable,Badge,SearchBox,Note} from './ui-parts';
import {KPI,Modal,Field,Actions} from './management-ui';

export function WorkbenchView({viewRole,viewerId,onOpen}:{viewRole:ViewRole;viewerId:string;onOpen:(page:string,context?:WorkContext)=>void}){
 const {state:s,mutate}=useManagement();const [category,setCategory]=useState('all'),[query,setQuery]=useState(''),[limit,setLimit]=useState(12),[editing,setEditing]=useState<Todo|null>(null),[owner,setOwner]=useState(viewerId),[due,setDue]=useState('');
 const items=visibleTodos(s,viewRole,viewerId);const filtered=items.filter(t=>(category==='all'||category==='overdue'&&!!t.due&&t.due<s.date||category==='soon'&&!!t.due&&t.due>=s.date&&t.due<=dayAfter(s.date,3))&&`${t.title} ${t.category} ${t.ownerLabel}`.includes(query));
 const gap=['POL-SCN-03','POL-SCN-05'].filter(id=>s.policies.some(p=>p.id===id)).reduce((n,id)=>n+supply(s,id,'SLOT-1').gap,0);
 const cards=viewRole==='员工'?[{label:'我的待办',value:items.length,note:'本人训练、补证和被分派事项'},{label:'我的培养计划',value:s.development.filter(d=>d.personId===viewerId).length,note:'统一计划保留课程、实践与复测记录',onClick:()=>onOpen('talent',{personId:viewerId})},{label:'我的评价进度',value:s.assessments.filter(a=>a.personId===viewerId&&a.status!=='已生效').length,note:'查看取证、提交及复核进度',onClick:()=>onOpen('evaluation',{personId:viewerId})},{label:'本人能力画像',value:personAt(s,viewerId).name,note:'当前能力、有效证据与成长方向',onClick:()=>onOpen('wall',{personId:viewerId,roleId:personAt(s,viewerId).roleId})}]:[{label:'当前视角待办',value:items.length,note:'来源记录更新后，清单同步更新'},{label:'当班独立保障缺口',value:gap,note:'14:00—15:00 · 报修与投诉场景',onClick:()=>onOpen('supply')},{label:'待评价复核',value:s.assessments.filter(a=>a.status==='待复核').length,note:'与场景上岗授权分别确认',onClick:()=>onOpen('evaluation')},{label:'培养目标待确认',value:s.development.filter(d=>developmentStatus(s,d)==='条件满足，待确认').length,note:'能力和实践满足后由负责人确认',onClick:()=>onOpen('talent')}];
 return <><KPI items={cards}/><section className="panel"><PanelTitle title={viewRole==='员工'?'我的待办':viewRole==='班组长'?`${personAt(s,viewerId).team} · 待办清单`:'待办与提醒'} sub={`${viewRole}视角 · 未设置期限的历史事项单独标识`} icon={<ListChecks size={20}/>}/><div className="mg-toolbar"><Segments value={category} onChange={setCategory} options={[{value:'all',label:`全部 ${items.length}`},{value:'overdue',label:`已逾期 ${items.filter(t=>t.due&&t.due<s.date).length}`},{value:'soon',label:'三日内到期'}]}/><SearchBox value={query} onChange={setQuery} placeholder="搜索事项、责任人或阶段"/></div><DataTable headers={['待办事项','当前阶段 / 下一步','责任人或责任角色','办理期限','操作']} rows={filtered.slice(0,limit).map(t=>[<div><b>{t.title}</b>{t.context.scenarioId&&<small className="cell-note">{nameOf(s,t.context.scenarioId)}</small>}</div>,<div><Badge tone="blue">{t.category}</Badge><small className="cell-note">{t.step}</small></div>,t.ownerLabel,<div><Badge tone={!t.due?'gray':t.due<s.date?'amber':'green'}>{t.due||'未设置期限'}</Badge>{t.due&&t.due<s.date&&<small className="cell-note">已逾期</small>}</div>,<Actions><button className="button primary" onClick={()=>onOpen(t.page,t.context)}>办理<ArrowUpRight size={14}/></button>{viewRole!=='员工'&&<button className="text-button" onClick={()=>{setEditing(t);setOwner(t.ownerId||viewerId);setDue(t.due)}}>分派</button>}</Actions>])}/>{filtered.length>limit&&<div className="mg-inset"><button className="button outline" onClick={()=>setLimit(limit+12)}>再显示 12 项 · 共 {filtered.length} 项</button></div>}</section><div className="v3-work-links"><button onClick={()=>onOpen('wall')}><Users/><div><b>岗位能力墙</b><span>从组织共性缺口追到人员和依据</span></div><ArrowUpRight/></button><button onClick={()=>onOpen('talent',{personId:viewerId})}><CalendarClock/><div><b>培养发展</b><span>同一份计划连接实践、评价与成长结果</span></div><ArrowUpRight/></button></div>
 <Modal open={!!editing} onClose={()=>setEditing(null)} title="分派办理责任与期限" sub={editing?.title||''}><Picker label="待办责任人" value={owner} onChange={setOwner} options={base.people.map(p=>({value:p.id,label:p.name}))}/><Field label="办理截止日期" type="date" value={due} onChange={e=>setDue(e.target.value)}/><Actions><button className="button primary" onClick={()=>{if(mutate(st=>{if(!editing||!due||!base.people.some(p=>p.id===owner))throw new Error('请填写责任人与期限');st.workspace!.todoAssignments[editing.id]={ownerId:owner,due,stage:`${editing.category}|${editing.step}`};if(editing.id.startsWith('action:')){const a=st.actions.find(a=>a.id===editing.context.recordId)!;a.due=due;if(a.status==='待办理')a.ownerId=owner}if(editing.id.startsWith('development:'))st.development.find(d=>d.id===editing.context.recordId)!.due=due;addAudit(st,'分派待办',`${editing.title} / ${nameOf(st,owner)} / ${due}`)}))setEditing(null)}}>保存分派</button></Actions><Note>阶段与完成状态来自原业务记录；责任分派不会代替评价复核或授权审批。</Note></Modal></>;
}
