const fs=require('fs');const path=require('path');const Module=require('module');const {createRequire}=Module;const root=path.resolve(__dirname,'..');const req=createRequire(path.join(root,'package.json'));const ts=req('typescript');
for(const ext of ['.ts','.tsx'])Module._extensions[ext]=(mod,file)=>{let source=fs.readFileSync(file,'utf8');source=source.replace(/(['"])@\/(.*?)\1/g,(_,quote,suffix)=>JSON.stringify(path.join(root,suffix).replaceAll('\\','/')));const code=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;mod._compile(code,file)};
const React=req('react');const {renderToStaticMarkup}=req('react-dom/server');const {ManagementProvider}=require(path.join(root,'app/management-context.tsx'));
const noop=()=>{};const modules=[['organization-view','OrganizationView',{onDetail:noop},'组织架构'],['governance-view','GovernanceView',{},'从岗位业务到数据清单'],['evaluation-view','AuthorizationView',{personId:'DEMO-013',onNavigate:noop,onPerson:noop},'场景上岗授权'],['evaluation-view','EvaluationView',{personId:'DEMO-013',onPerson:noop,onDetail:noop},'能力评价'],['operations-view','SupplyView',{onNavigate:noop,onPerson:noop},'组织能力供需与风险预警'],['operations-view','DiagnosisView',{onNavigate:noop,onDetail:noop},'业务结果与能力诊断'],['talent-view','TalentView',{onNavigate:noop,onPerson:noop},'人才梯队与岗位发展路径'],['wall-view','WallView',{roleId:'ROLE-02',setRoleId:noop,onDetail:noop,onGrowth:noop},'主要成长方向']];
modules.push(['workbench-view','WorkbenchView',{viewRole:'管理者',viewerId:'DEMO-016',onOpen:noop,onDetail:noop},'待办与提醒'],['organization-matrix','OrganizationMatrix',{roleId:'ROLE-02',onRole:noop,onOpen:noop},'组织能力矩阵'],['maintenance-tools','HandoffView',{editable:true},'跨岗位协同责任标准'],['maintenance-tools','TemplateView',{},'模板与批量维护'],['workspace-v3','default',{},'工作台']);
modules.push(['business-view','BusinessView',{roleId:'ROLE-01',onDetail:noop},'附件依据与口径说明'],['data-view','DataView',{assetId:'ASSET-06',setAssetId:noop,tab:'catalog',setTab:noop,onDetail:noop},'知识内容与版本样本'],['reference-panels','ReferenceJobs',{onDetail:noop},'首席客服专员'],['graph-view','GraphView',{roleId:'ROLE-01',setRoleId:noop,onDetail:noop,onNavigate:noop,explorer:true},'图谱能力族']);
modules.push(['maintenance-tools','HandoffView',{roleId:'ROLE-01'},'模拟案例']);
modules.push(['team-structure','TeamStructureView',{onDetail:noop},'登记职级分布']);
modules.push(['person-capability-plan-view','PersonCapabilityPlan',{person:require(path.join(root,'app/model.ts')).personById('DEMO-013'),onDetail:noop},'下载能力清单']);
modules.push(['matrix-improvement-view','MatrixImprovementView',{personId:'DEMO-002',roleId:'ROLE-01',star:3,initialCapabilityId:'CAP-02',onBack:noop},'准备这些材料']);
modules.push(['person-roles','PersonRoles',{personId:'DEMO-001'},'一人多岗']);
const results=[];for(const [file,name,props,text] of modules){try{const component=require(path.join(root,`app/${file}.tsx`))[name];const markup=renderToStaticMarkup(React.createElement(ManagementProvider,null,React.createElement(component,props)));if(!markup.includes(text))throw new Error('Expected main content missing');if(name==='WorkbenchView'&&(!markup.includes('队伍结构')||markup.includes('workbench-view-switcher')))throw new Error('Workbench must show both sections together');if(name==='HandoffView'&&(!markup.includes('反馈时间与问题处理')||markup.includes('复核 / 升级岗位')))throw new Error('Plain handoff language missing');if(/NaN|undefined%/.test(markup))throw new Error('Invalid numeric output');results.push({component:name,passed:true,bytes:Buffer.byteLength(markup)})}catch(e){results.push({component:name,passed:false,error:e.stack});}}
fs.writeFileSync('work/management-render-verification.json',JSON.stringify({kind:'React server rendering only; not browser or visual QA',results},null,2));console.log(JSON.stringify(results.map(r=>({component:r.component,passed:r.passed,error:r.error})),null,2));if(results.some(r=>!r.passed))process.exitCode=1;
